#!/usr/bin/env tsx
/** review-batch-006: zero-proof / low-ABV depth + classic variety gaps */
import * as fs from 'fs';
import * as path from 'path';

type Draft = {
  slug: string; name: string; short_description: string; long_description: string; seo_description: string;
  base_spirit: string; category_primary: string; categories_all: string; tags: string; image_alt: string;
  glassware: string; garnish: string; technique: 'Shake' | 'Stir' | 'Build' | 'Blend' | 'Swizzle';
  difficulty: 'Easy' | 'Intermediate' | 'Advanced';
  flavor_strength: number; flavor_sweetness: number; flavor_tartness: number; flavor_bitterness: number;
  flavor_aroma: number; flavor_texture: number;
  notes: string; fun_fact: string; fun_fact_source: string; ingredients: string; instructions: string;
};

const drafts: Draft[] = [
  {
    slug: 'shirley-temple',
    name: 'Shirley Temple',
    short_description: 'A classic non-alcoholic highball of ginger ale and grenadine, finished with a cherry.',
    long_description: 'The Shirley Temple is the default kid-friendly bar mocktail: ginger ale sweetened and colored with grenadine, served over ice with a cherry. It is bright, fizzy, and deliberately simple—useful as a hosting default when someone wants a dressed drink without alcohol.',
    seo_description: 'Build a Shirley Temple with ginger ale and grenadine for a classic non-alcoholic highball.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Highball', categories_all: 'mocktail|highball|zero-proof|hosting',
    tags: 'zero-proof|mocktail|ginger-ale|grenadine|cherry|kid-friendly',
    image_alt: 'Shirley Temple in a highball over ice, pink-amber ginger ale, cherry garnish.',
    glassware: 'Highball glass', garnish: 'maraschino cherry', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 1, flavor_sweetness: 8, flavor_tartness: 1, flavor_bitterness: 0, flavor_aroma: 3, flavor_texture: 4,
    notes: 'Use real ginger ale, not plain soda. A splash of fresh lime keeps the sweetness in check for adults.',
    fun_fact: 'Named for the child star Shirley Temple, the drink became a mid-century American restaurant staple for guests who wanted a cocktail-looking soda.',
    fun_fact_source: 'American bar and restaurant drink histories',
    ingredients: '4 oz ginger ale|0.5 oz grenadine|1 maraschino cherry',
    instructions: '1. Fill a highball with ice. 2. Add grenadine. 3. Top with ginger ale and stir gently. 4. Garnish with a cherry.',
  },
  {
    slug: 'virgin-mary',
    name: 'Virgin Mary',
    short_description: 'A non-alcoholic Bloody Mary: tomato juice, savory seasonings, and a celery stick.',
    long_description: 'The Virgin Mary keeps the Bloody Mary’s tomato-savory profile without vodka. Horseradish, hot sauce, Worcestershire, citrus, and celery salt still define the drink. Served tall over ice, it is the clearest zero-proof brunch option in the spicy-savory lane.',
    seo_description: 'Build a Virgin Mary with tomato juice and savory seasonings for a zero-proof Bloody Mary.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Savory', categories_all: 'mocktail|savory|zero-proof|brunch',
    tags: 'zero-proof|mocktail|tomato|spicy|brunch|celery',
    image_alt: 'Virgin Mary in a highball over ice, opaque red tomato drink, celery stalk and lime.',
    glassware: 'Highball glass', garnish: 'celery stalk|lime wedge', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 3, flavor_sweetness: 2, flavor_tartness: 4, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 5,
    notes: 'Taste and adjust heat and salt before pouring. A light celery-salt rim is optional.',
    fun_fact: 'Calling a Bloody Mary without vodka a Virgin Mary became standard brunch language as non-drinkers asked for the same savory profile.',
    fun_fact_source: 'Brunch and mocktail menu practice',
    ingredients: '4 oz tomato juice|0.5 oz fresh lemon juice|2 dashes Worcestershire sauce|2 dashes hot sauce|1 pinch celery salt|1 pinch black pepper|horseradish to taste',
    instructions: '1. Combine tomato juice, lemon, Worcestershire, hot sauce, celery salt, pepper, and horseradish in a glass. 2. Add ice and stir. 3. Garnish with celery and lime.',
  },
  {
    slug: 'arnold-palmer',
    name: 'Arnold Palmer',
    short_description: 'Half iced tea and half lemonade—a classic American non-alcoholic cooler.',
    long_description: 'The Arnold Palmer mixes iced tea and lemonade in roughly equal parts over ice. Tea bitterness balances lemonade sweetness for an easy patio drink. It is one of the most recognized zero-proof coolers in American hosting.',
    seo_description: 'Build an Arnold Palmer with iced tea and lemonade for a classic zero-proof cooler.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Highball', categories_all: 'mocktail|highball|zero-proof|summer',
    tags: 'zero-proof|mocktail|iced-tea|lemonade|summer|hosting',
    image_alt: 'Arnold Palmer in a highball over ice, amber-gold tea-lemonade, lemon wedge optional omit if preferred.',
    glassware: 'Highball glass', garnish: 'lemon wedge optional', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 1, flavor_sweetness: 5, flavor_tartness: 5, flavor_bitterness: 2, flavor_aroma: 4, flavor_texture: 4,
    notes: 'Brew tea strong enough to stand up to lemonade. Adjust the ratio toward tea for a drier adult version.',
    fun_fact: 'Golfer Arnold Palmer popularized the iced-tea-and-lemonade mix; bars later called the spiked version a John Daly.',
    fun_fact_source: 'American iced-tea drink lore',
    ingredients: '3 oz brewed iced tea|3 oz lemonade',
    instructions: '1. Fill a highball with ice. 2. Add iced tea and lemonade. 3. Stir briefly. 4. Garnish with lemon if desired.',
  },
  {
    slug: 'virgin-mojito',
    name: 'Virgin Mojito',
    short_description: 'A zero-proof mojito of mint, lime, sugar, and soda over ice.',
    long_description: 'The Virgin Mojito keeps mint, lime, and sugar from the classic Cuban highball and skips the rum. Muddled mint oils and bright citrus still read as a mojito once soda lengthens the drink. It is a reliable summer zero-proof call.',
    seo_description: 'Build a Virgin Mojito with mint, lime, sugar, and soda for a classic zero-proof highball.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Highball', categories_all: 'mocktail|highball|zero-proof|mint',
    tags: 'zero-proof|mocktail|mint|lime|soda|summer',
    image_alt: 'Virgin Mojito in a highball over ice, pale, mint sprig bouquet.',
    glassware: 'Highball glass', garnish: 'mint sprig', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 1, flavor_sweetness: 4, flavor_tartness: 6, flavor_bitterness: 0, flavor_aroma: 8, flavor_texture: 4,
    notes: 'Muddle mint gently with sugar and lime—do not shred the leaves into bitterness.',
    fun_fact: 'Virgin mojitos became a default restaurant mocktail because the mint-lime-soda structure still feels like a composed cocktail without rum.',
    fun_fact_source: 'Modern restaurant mocktail menus',
    ingredients: '8-10 mint leaves|0.75 oz fresh lime juice|0.5 oz simple syrup|4 oz club soda',
    instructions: '1. Gently muddle mint with syrup and lime in a highball. 2. Add ice. 3. Top with soda and stir once. 4. Garnish with a mint sprig.',
  },
  {
    slug: 'no-groni',
    name: 'No-Groni',
    short_description: 'A zero-proof Negroni template with non-alcoholic gin, bitter aperitif, and vermouth alternatives.',
    long_description: 'The No-Groni mirrors the equal-parts Negroni with non-alcoholic gin, non-alcoholic bitter aperitif, and non-alcoholic sweet vermouth. Bitterness and orange still define the profile; the body is lighter without ethanol heat. Stirred and served over ice, it is the craft zero-proof answer to a Negroni order.',
    seo_description: 'Stir a No-Groni with non-alcoholic gin, bitter aperitif, and vermouth for a zero-proof Negroni.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Spirit-Forward', categories_all: 'mocktail|spirit-forward|zero-proof|negroni-family',
    tags: 'zero-proof|mocktail|negroni|bitter|stirred|craft',
    image_alt: 'No-Groni in a rocks glass over a large cube, deep orange-red, orange peel.',
    glassware: 'Rocks glass', garnish: 'orange peel', technique: 'Stir', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 7, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Equal parts keep the architecture. Brand choice for NA bitter and vermouth changes the drink more than technique does.',
    fun_fact: 'No-Groni and similar NA Negroni riffs grew with the craft non-alcoholic spirits boom of the late 2010s.',
    fun_fact_source: 'Modern zero-proof cocktail practice',
    ingredients: '1 oz non-alcoholic gin|1 oz non-alcoholic bitter aperitif|1 oz non-alcoholic sweet vermouth',
    instructions: '1. Stir all ingredients with ice. 2. Strain over a large ice cube. 3. Garnish with an expressed orange peel.',
  },
  {
    slug: 'zero-proof-margarita',
    name: 'Zero-Proof Margarita',
    short_description: 'A non-alcoholic margarita with lime, agave, and orange, optional salt rim.',
    long_description: 'The Zero-Proof Margarita keeps lime, agave sweetness, and orange character without tequila. Non-alcoholic agave spirit is ideal; without it, a measured mix of lime, agave syrup, and orange juice still lands in margarita territory when shaken and salted. Served on the rocks, it fills a major hosting gap.',
    seo_description: 'Shake a Zero-Proof Margarita with lime, agave, and orange for a non-alcoholic margarita.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Sour', categories_all: 'mocktail|sour|zero-proof|margarita-family',
    tags: 'zero-proof|mocktail|lime|agave|margarita',
    image_alt: 'Zero-Proof Margarita in a rocks glass over ice, pale green, lime wheel, salt rim.',
    glassware: 'Rocks glass', garnish: 'lime wheel|optional salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 2, flavor_sweetness: 4, flavor_tartness: 7, flavor_bitterness: 0, flavor_aroma: 5, flavor_texture: 5,
    notes: 'If using NA tequila, treat it like blanco. Without it, keep orange juice measured so the drink stays tart.',
    fun_fact: 'Zero-proof margaritas became one of the most requested NA cocktail templates as tequila culture and dry dining grew together.',
    fun_fact_source: 'Modern zero-proof bar menus',
    ingredients: '2 oz non-alcoholic tequila alternative or 1.5 oz cold water + 0.5 oz orange juice|1 oz fresh lime juice|0.75 oz agave syrup|0.5 oz orange juice if using NA tequila|optional salt rim',
    instructions: '1. Optional salt half-rim. 2. Shake all liquid ingredients with ice. 3. Strain over fresh ice. 4. Garnish with lime.',
  },
  {
    slug: 'zero-proof-mule',
    name: 'Zero-Proof Mule',
    short_description: 'A Moscow Mule without vodka: ginger beer, lime, and mint over ice.',
    long_description: 'The Zero-Proof Mule keeps ginger beer and lime from the Moscow Mule and omits vodka. Spicy ginger and citrus still define the highball. Served in a copper mug or highball, it is an easy zero-proof swap for mule drinkers.',
    seo_description: 'Build a Zero-Proof Mule with ginger beer and lime for a non-alcoholic Moscow Mule.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Highball', categories_all: 'mocktail|highball|zero-proof|mule',
    tags: 'zero-proof|mocktail|ginger-beer|lime|mule',
    image_alt: 'Zero-Proof Mule in a copper mug or highball over ice, pale ginger, mint sprig.',
    glassware: 'Copper mug', garnish: 'mint sprig|lime wedge', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 2, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 4,
    notes: 'Use a spicy ginger beer. A splash of soda lightens overly sweet brands.',
    fun_fact: 'Non-alcoholic mules spread quickly because ginger beer already carries most of the classic mule’s flavor.',
    fun_fact_source: 'Modern mule and mocktail menus',
    ingredients: '4 oz ginger beer|0.75 oz fresh lime juice|mint sprig',
    instructions: '1. Fill a copper mug or highball with ice. 2. Add lime juice. 3. Top with ginger beer and stir once. 4. Garnish with mint and lime.',
  },
  {
    slug: 'hibiscus-cooler',
    name: 'Hibiscus Cooler',
    short_description: 'A tart floral zero-proof cooler of hibiscus tea, citrus, and soda.',
    long_description: 'The Hibiscus Cooler builds on chilled hibiscus (agua de Jamaica–style) tea with citrus and soda. Deep red color and cranberry-like tartness make it feel composed without alcohol. It is a strong hosting mocktail when you want something less sugary than a Shirley Temple.',
    seo_description: 'Build a Hibiscus Cooler with hibiscus tea, citrus, and soda for a floral zero-proof highball.',
    base_spirit: 'Non-Alcoholic', category_primary: 'Highball', categories_all: 'mocktail|highball|zero-proof|floral',
    tags: 'zero-proof|mocktail|hibiscus|citrus|soda|hosting',
    image_alt: 'Hibiscus Cooler in a highball over ice, deep ruby red, mint or orange peel.',
    glassware: 'Highball glass', garnish: 'orange peel|mint sprig', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 2, flavor_sweetness: 4, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 4,
    notes: 'Brew hibiscus strong, then chill. Sweeten lightly—the flower is already tart.',
    fun_fact: 'Hibiscus coolers borrow from agua de Jamaica and Caribbean/Mexican agua fresca traditions adapted into modern mocktail service.',
    fun_fact_source: 'Agua de Jamaica and modern mocktail practice',
    ingredients: '3 oz chilled hibiscus tea|0.5 oz fresh lime juice|0.5 oz simple syrup|2 oz club soda',
    instructions: '1. Build hibiscus, lime, and syrup over ice. 2. Top with soda and stir gently. 3. Garnish with orange peel or mint.',
  },
  {
    slug: 'vermouth-tonic',
    name: 'Vermouth Tonic',
    short_description: 'A low-ABV highball of vermouth lengthened with tonic and citrus.',
    long_description: 'Vermouth Tonic pours fortified wine over ice and tops it with tonic. Blanc or dry vermouth stays crisp; sweet vermouth reads richer. It is a sessionable aperitif highball with far less strength than a spirit-forward cocktail.',
    seo_description: 'Build a Vermouth Tonic with vermouth and tonic water for a low-ABV aperitif highball.',
    base_spirit: 'Vermouth', category_primary: 'Highball', categories_all: 'low-abv|highball|aperitif|vermouth',
    tags: 'low-abv|vermouth|tonic|aperitif|sessionable',
    image_alt: 'Vermouth Tonic in a highball over ice, pale gold, orange or grapefruit peel.',
    glassware: 'Highball glass', garnish: 'orange peel|grapefruit peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 3, flavor_sweetness: 3, flavor_tartness: 2, flavor_bitterness: 4, flavor_aroma: 6, flavor_texture: 4,
    notes: 'Blanc vermouth is the most crowd-pleasing. Keep tonic cold and not overly sweet.',
    fun_fact: 'Vermouth-and-tonic highballs surged in Spain and modern aperitivo bars as drinkers sought lower-ABV daytime options.',
    fun_fact_source: 'Spanish and modern aperitivo highball practice',
    ingredients: '2 oz blanc or dry vermouth|4 oz tonic water',
    instructions: '1. Fill a highball with ice. 2. Add vermouth. 3. Top with tonic and stir once. 4. Garnish with citrus peel.',
  },
  {
    slug: 'tinto-de-verano',
    name: 'Tinto de Verano',
    short_description: 'A Spanish low-ABV cooler of red wine and lemon soda over ice.',
    long_description: 'Tinto de Verano (“red wine of summer”) mixes red wine with lemon soda or gaseosa over ice. It is lighter and less bitter than a Kalimotxo (wine and cola) and built for heat. Served tall, it is a classic European low-ABV hosting drink.',
    seo_description: 'Build a Tinto de Verano with red wine and lemon soda for a Spanish low-ABV cooler.',
    base_spirit: 'Wine', category_primary: 'Highball', categories_all: 'low-abv|highball|wine|spanish|summer',
    tags: 'low-abv|wine|lemon-soda|spanish|summer',
    image_alt: 'Tinto de Verano in a highball over ice, ruby wine cooler, orange slice.',
    glassware: 'Highball glass', garnish: 'orange slice', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 3, flavor_sweetness: 4, flavor_tartness: 4, flavor_bitterness: 1, flavor_aroma: 4, flavor_texture: 4,
    notes: 'Use an inexpensive young red. Lemon soda (or lemonade lightly cut with soda) beats plain Sprite for balance.',
    fun_fact: 'Tinto de Verano is a Spanish summer staple—often more common at casual terraces than sangria.',
    fun_fact_source: 'Spanish everyday drink culture',
    ingredients: '3 oz red wine|3 oz lemon soda',
    instructions: '1. Fill a highball with ice. 2. Add wine and lemon soda. 3. Stir gently. 4. Garnish with an orange slice.',
  },
  {
    slug: 'campari-soda',
    name: 'Campari Soda',
    short_description: 'A simple low-ABV aperitivo of Campari lengthened with soda.',
    long_description: 'Campari Soda is Campari over ice topped with club soda—the skeleton of the Americano without vermouth. Bitter orange stays loud while soda softens the proof. It is a minimal Italian aperitivo highball.',
    seo_description: 'Build a Campari Soda with Campari and club soda for a classic low-ABV aperitivo.',
    base_spirit: 'Aperitif', category_primary: 'Highball', categories_all: 'low-abv|highball|aperitif|campari',
    tags: 'low-abv|campari|soda|aperitif|italian',
    image_alt: 'Campari Soda in a highball over ice, bright red, orange peel.',
    glassware: 'Highball glass', garnish: 'orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 8, flavor_aroma: 7, flavor_texture: 4,
    notes: 'Start with 1.5 oz Campari if guests are bitter-shy. Keep soda ice-cold.',
    fun_fact: 'Campari and soda predates many modern spritzes as a straightforward Italian café aperitivo.',
    fun_fact_source: 'Italian aperitivo tradition',
    ingredients: '2 oz Campari|4 oz club soda',
    instructions: '1. Build Campari over ice in a highball. 2. Top with soda and stir once. 3. Garnish with an orange peel.',
  },
  {
    slug: 'john-collins',
    name: 'John Collins',
    short_description: 'A whiskey Collins: spirit, lemon, sugar, and soda in a tall glass.',
    long_description: 'The John Collins applies the Collins template to whiskey instead of gin. Lemon, sugar, and soda keep it bright while whiskey adds warmth. Served tall over ice, it sits beside the Tom Collins as a core sparkling sour-highball.',
    seo_description: 'Build a John Collins with whiskey, lemon, sugar, and soda for a classic whiskey highball sour.',
    base_spirit: 'Whiskey', category_primary: 'Highball', categories_all: 'classic|highball|sour|whiskey|collins',
    tags: 'whiskey|lemon|soda|collins|classic',
    image_alt: 'John Collins in a Collins glass over ice, pale gold, cherry optional.',
    glassware: 'Collins glass', garnish: 'orange slice|cherry optional', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 4, flavor_texture: 4,
    notes: 'Bourbon is common; rye makes it drier. Shake whiskey, lemon, and sugar first if you want a colder, frothier start, then top with soda.',
    fun_fact: 'Collins family drinks share a 19th-century highball-sour structure; the John Collins specifies whiskey where the Tom uses gin.',
    fun_fact_source: 'Classic Collins family histories',
    ingredients: '2 oz bourbon or whiskey|1 oz fresh lemon juice|0.5 oz simple syrup|3 oz club soda',
    instructions: '1. Shake whiskey, lemon, and syrup with ice (or build). 2. Strain into a Collins glass over ice. 3. Top with soda. 4. Garnish with orange and optional cherry.',
  },
  {
    slug: 'rose-cocktail',
    name: 'Rose',
    short_description: 'A French aperitif cocktail of gin, cherry brandy, and dry vermouth.',
    long_description: 'The Rose is a pale French aperitif built on gin with kirsch or cherry brandy and dry vermouth, often with a touch of syrup or currant. It is delicate, floral-fruity, and stirred. The drink fills a classic gap between a Martini and a fruit-forward aperitif.',
    seo_description: 'Stir a Rose cocktail with gin, cherry brandy, and dry vermouth for a classic French aperitif.',
    base_spirit: 'Gin', category_primary: 'Spirit-Forward', categories_all: 'classic|spirit-forward|aperitif|french|gin',
    tags: 'gin|kirsch|vermouth|french|aperitif',
    image_alt: 'Rose cocktail in a coupe, pale pink, cherry garnish.',
    glassware: 'Coupe', garnish: 'brandied cherry', technique: 'Stir', difficulty: 'Intermediate',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 2, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Recipes vary; keep cherry brandy light so the drink stays aperitif-dry rather than dessert-sweet.',
    fun_fact: 'The Rose appears in early-20th-century French cocktail books as a Parisian aperitif, distinct from the wine-based Kir.',
    fun_fact_source: 'Early French cocktail manuals',
    ingredients: '2 oz gin|1 oz dry vermouth|0.5 oz kirsch or cherry brandy|1 dash raspberry syrup optional',
    instructions: '1. Stir all ingredients with ice. 2. Strain into a chilled coupe. 3. Garnish with a cherry.',
  },
  {
    slug: 'golden-dream',
    name: 'Golden Dream',
    short_description: 'A creamy after-dinner cocktail of Galliano, Cointreau, orange juice, and cream.',
    long_description: 'The Golden Dream shakes Galliano and Cointreau with orange juice and cream into a soft, golden dessert cocktail. Vanilla-anise from Galliano meets orange and dairy for a classic IBA-style digestif sour-cream hybrid. Served up, it is a vintage dessert-drink anchor.',
    seo_description: 'Shake a Golden Dream with Galliano, Cointreau, orange juice, and cream.',
    base_spirit: 'Liqueur', category_primary: 'Dessert', categories_all: 'classic|dessert|cream|galliano',
    tags: 'galliano|cointreau|cream|orange|dessert',
    image_alt: 'Golden Dream in a coupe, opaque pale gold cream, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 7, flavor_tartness: 2, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 8,
    notes: 'Shake hard with ice for a thick foam. Fresh orange juice beats sour mix.',
    fun_fact: 'The Golden Dream is an IBA official cocktail associated with mid-century creamy after-dinner drinks built on Galliano.',
    fun_fact_source: 'IBA cocktail lists; mid-century dessert cocktail histories',
    ingredients: '0.75 oz Galliano|0.75 oz Cointreau|0.75 oz fresh orange juice|0.75 oz cream',
    instructions: '1. Shake all ingredients hard with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'japanese-highball',
    name: 'Japanese Highball',
    short_description: 'A precise whisky-and-soda highball built for clarity, cold, and fine bubbles.',
    long_description: 'The Japanese Highball treats whisky and soda as a craft ritual: well-chilled glass, hard clear ice, measured whisky, and cold soda poured to preserve carbonation. It is lighter than a rocks pour and cleaner than a casual Scotch-and-soda. Technique and temperature matter as much as the whisky.',
    seo_description: 'Build a Japanese Highball with whisky and soda over clear ice for a crisp low-dilution highball.',
    base_spirit: 'Whiskey', category_primary: 'Highball', categories_all: 'classic|highball|whisky|japanese|sessionable',
    tags: 'whisky|soda|highball|japanese|sessionable',
    image_alt: 'Japanese Highball in a tall highball with clear ice spears, pale gold, no garnish or lemon twist optional omit.',
    glassware: 'Highball glass', garnish: 'None', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 1, flavor_tartness: 0, flavor_bitterness: 1, flavor_aroma: 5, flavor_texture: 4,
    notes: 'Chill the glass and soda. Pour soda gently down the side or along a barspoon to keep bubbles fine. A 1:3 or 1:4 whisky-to-soda ratio is common.',
    fun_fact: 'Japan’s highball boom made whisky-and-soda a precision drink again, with bars obsessing over ice clarity and carbonation.',
    fun_fact_source: 'Japanese whisky highball service culture',
    ingredients: '2 oz Japanese whisky or blended whisky|4-6 oz chilled club soda',
    instructions: '1. Add large clear ice to a chilled highball. 2. Pour whisky and briefly stir to chill. 3. Top with cold soda. 4. Stir once vertically to integrate; serve ungarnished.',
  },
];

function csvEscape(v: string | number) {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main() {
  const headers = ['ID','slug','name','short_description','long_description','seo_description','base_spirit','category_primary','categories_all','tags','image_url','image_alt','glassware','garnish','technique','difficulty','flavor_strength','flavor_sweetness','flavor_tartness','flavor_bitterness','flavor_aroma','flavor_texture','notes','fun_fact','fun_fact_source','metadata_json','ingredients','instructions'];
  const rows = drafts.map((d, i) =>
    [`mw_review_006_${String(i + 1).padStart(3, '0')}`, d.slug, d.name, d.short_description, d.long_description, d.seo_description, d.base_spirit, d.category_primary, d.categories_all, d.tags, '', d.image_alt, d.glassware, d.garnish, d.technique, d.difficulty, d.flavor_strength, d.flavor_sweetness, d.flavor_tartness, d.flavor_bitterness, d.flavor_aroma, d.flavor_texture, d.notes, d.fun_fact, d.fun_fact_source, '{}', d.ingredients, d.instructions]
      .map(csvEscape)
      .join(',')
  );
  const out = path.join(process.cwd(), 'data', 'review-batch-006.csv');
  fs.writeFileSync(out, [headers.join(','), ...rows].join('\n') + '\n');
  console.log(`Wrote ${drafts.length} → ${out}`);
  console.log(drafts.map((d) => d.slug).join('\n'));
}

main();
