#!/usr/bin/env tsx
/** Generate review-batch-004.csv — holiday-themed drinks. */
import * as fs from 'fs';
import * as path from 'path';

type Draft = {
  slug: string; name: string; short_description: string; long_description: string; seo_description: string;
  base_spirit: string; category_primary: string; categories_all: string; tags: string; image_alt: string;
  glassware: string; garnish: string; technique: 'Shake' | 'Stir' | 'Build' | 'Blend' | 'Swizzle';
  difficulty: 'Easy' | 'Intermediate' | 'Advanced';
  flavor_strength: number; flavor_sweetness: number; flavor_tartness: number; flavor_bitterness: number;
  flavor_aroma: number; flavor_texture: number;
  notes: string; fun_fact: string; fun_fact_source: string; ingredients: string; instructions: string;
};

const drafts: Draft[] = [
  {
    slug: 'eggnog',
    name: 'Eggnog',
    short_description: 'A rich holiday punch of eggs, milk, cream, sugar, and spirit, finished with nutmeg.',
    long_description: 'Eggnog is a festive dairy-and-egg punch fortified with brandy, rum, or whiskey. Sugar and spice round the dairy, while nutmeg finishes the aroma. Served cold in a punch cup or mug, it is one of the core Christmas and winter holiday drinks in North America.',
    seo_description: 'Make classic Eggnog with eggs, milk, cream, sugar, and brandy or rum for a holiday punch.',
    base_spirit: 'Brandy', category_primary: 'Punch', categories_all: 'holiday|christmas|winter|punch|dessert',
    tags: 'eggnog|brandy|rum|nutmeg|christmas',
    image_alt: 'Eggnog in a punch cup, creamy pale, nutmeg dusting.',
    glassware: 'Mug', garnish: 'grated nutmeg', technique: 'Build', difficulty: 'Intermediate',
    flavor_strength: 5, flavor_sweetness: 7, flavor_tartness: 0, flavor_bitterness: 0, flavor_aroma: 7, flavor_texture: 9,
    notes: 'Use pasteurized eggs if preferred. Chill thoroughly before serving. Spirit choice is flexible.',
    fun_fact: 'Eggnog descends from earlier British milk-and-egg possets and became a staple of American holiday entertaining.',
    fun_fact_source: 'British and American holiday drink histories',
    ingredients: '1 oz brandy|1 oz dark rum|1 whole egg|1 oz simple syrup|2 oz whole milk|1 oz heavy cream|grated nutmeg',
    instructions: '1. Shake egg, syrup, and spirits without ice until frothy. 2. Add milk, cream, and ice; shake again. 3. Strain into a chilled cup. 4. Dust with nutmeg.',
  },
  {
    slug: 'coquito',
    name: 'Coquito',
    short_description: 'A Puerto Rican coconut holiday punch with rum, spices, and condensed milk.',
    long_description: 'Coquito is a coconut-forward holiday punch associated with Puerto Rican Christmas celebrations. Rum, coconut milk or cream of coconut, sweetened condensed milk, and warm spices create a rich, fragrant drink served cold in small glasses. It is festive, batchable, and distinct from eggnog.',
    seo_description: 'Make Coquito with rum, coconut, condensed milk, and spice for a classic Puerto Rican holiday punch.',
    base_spirit: 'Rum', category_primary: 'Punch', categories_all: 'holiday|christmas|punch|caribbean',
    tags: 'rum|coconut|coquito|cinnamon|christmas',
    image_alt: 'Coquito in a small glass, creamy white, cinnamon dusting.',
    glassware: 'Rocks glass', garnish: 'ground cinnamon', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 8, flavor_tartness: 0, flavor_bitterness: 0, flavor_aroma: 8, flavor_texture: 9,
    notes: 'Blend and chill overnight for best texture. Adjust rum to taste; white or gold rum both work.',
    fun_fact: 'Coquito is a Puerto Rican Christmas tradition, often made in batches and shared among family and neighbors.',
    fun_fact_source: 'Puerto Rican holiday foodways',
    ingredients: '2 oz white rum|2 oz cream of coconut|2 oz sweetened condensed milk|2 oz evaporated milk|0.25 tsp vanilla|pinch cinnamon|pinch nutmeg',
    instructions: '1. Blend all ingredients until smooth. 2. Chill thoroughly. 3. Serve cold in small glasses. 4. Dust with cinnamon.',
  },
  {
    slug: 'peppermint-martini',
    name: 'Peppermint Martini',
    short_description: 'A holiday dessert martini with vodka, peppermint, and white chocolate or cream liqueur.',
    long_description: 'The Peppermint Martini is a Christmas party cocktail built from vodka and peppermint flavor with a creamy or white-chocolate liqueur base. Shaken and served up, it is minty, sweet, and explicitly festive. A light hand with peppermint keeps it from tasting like mouthwash.',
    seo_description: 'Shake a Peppermint Martini with vodka and peppermint liqueur for a Christmas dessert cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'holiday|christmas|dessert|party',
    tags: 'vodka|peppermint|cream|christmas|martini',
    image_alt: 'Peppermint Martini in a coupe, pale creamy white, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 7, flavor_tartness: 0, flavor_bitterness: 0, flavor_aroma: 8, flavor_texture: 7,
    notes: 'Start with less peppermint schnapps than you think. Optional crushed-candy rim is often too sweet for catalog photography.',
    fun_fact: 'Peppermint martinis became Christmas-menu staples alongside other dessert martinis in early-2000s American bars.',
    fun_fact_source: 'Modern holiday cocktail menus',
    ingredients: '1.5 oz vodka|1 oz white chocolate or Irish cream liqueur|0.5 oz peppermint schnapps|0.5 oz white crème de cacao optional',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'gingerbread-martini',
    name: 'Gingerbread Martini',
    short_description: 'A spiced holiday dessert martini with vodka, gingerbread syrup, and cream liqueur.',
    long_description: 'The Gingerbread Martini translates gingerbread-cookie spice into a shaken dessert cocktail. Vodka and cream liqueur carry ginger, molasses, and spice syrup. Served up, it is a recognizable Christmas and winter party drink.',
    seo_description: 'Shake a Gingerbread Martini with vodka, gingerbread syrup, and cream liqueur for a holiday cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'holiday|christmas|dessert|party',
    tags: 'vodka|gingerbread|spice|cream|christmas',
    image_alt: 'Gingerbread Martini in a coupe, light brown, spice dusting.',
    glassware: 'Coupe', garnish: 'grated nutmeg', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 7, flavor_tartness: 0, flavor_bitterness: 1, flavor_aroma: 8, flavor_texture: 7,
    notes: 'Homemade gingerbread syrup beats artificial mixes. Keep total sweetness in check.',
    fun_fact: 'Gingerbread cocktails followed the broader holiday dessert-flavor trend into winter bar menus.',
    fun_fact_source: 'Modern seasonal dessert cocktail menus',
    ingredients: '1.5 oz vodka|1 oz Irish cream|0.75 oz gingerbread syrup|0.5 oz coffee liqueur optional',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Dust with nutmeg.',
  },
  {
    slug: 'cranberry-cosmo',
    name: 'Cranberry Cosmo',
    short_description: 'A Thanksgiving-leaning Cosmopolitan with a stronger cranberry emphasis.',
    long_description: 'The Cranberry Cosmo keeps the Cosmopolitan’s vodka, orange liqueur, and citrus frame while leaning harder into cranberry for holiday color and tartness. Shaken and served up, it fits Thanksgiving and Christmas entertaining without reinventing the template.',
    seo_description: 'Shake a Cranberry Cosmo with vodka, cranberry, orange liqueur, and lime for a holiday cocktail.',
    base_spirit: 'Vodka', category_primary: 'Sour', categories_all: 'holiday|thanksgiving|sour|party',
    tags: 'vodka|cranberry|lime|cosmo|thanksgiving',
    image_alt: 'Cranberry Cosmo in a coupe, deep pink-red, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 4, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 5, flavor_texture: 5,
    notes: 'Use real cranberry juice cocktail or a mix of juice and simple syrup; avoid overly sweet bottled mixes.',
    fun_fact: 'Cranberry-forward Cosmo variations are common Thanksgiving menu specials because cranberry already signals the holiday table.',
    fun_fact_source: 'American holiday cocktail menu practice',
    ingredients: '1.5 oz citrus vodka|1 oz cranberry juice|0.75 oz Cointreau|0.5 oz fresh lime juice',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'cranberry-margarita',
    name: 'Cranberry Margarita',
    short_description: 'A tequila margarita brightened with cranberry for holiday color and tartness.',
    long_description: 'The Cranberry Margarita preserves tequila, lime, and orange liqueur while adding cranberry for seasonal tartness and color. Served on the rocks, it works for Thanksgiving and Christmas parties where a familiar margarita template is welcome with a holiday accent.',
    seo_description: 'Shake a Cranberry Margarita with tequila, cranberry, lime, and orange liqueur for a holiday twist.',
    base_spirit: 'Tequila', category_primary: 'Sour', categories_all: 'holiday|thanksgiving|sour|margarita-family',
    tags: 'tequila|cranberry|lime|margarita|holiday',
    image_alt: 'Cranberry Margarita in a rocks glass over ice, red-pink, optional salt rim.',
    glassware: 'Rocks glass', garnish: 'lime wheel|optional salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 5, flavor_texture: 5,
    notes: 'Keep cranberry modest so lime and tequila stay present. Half salt rim is enough.',
    fun_fact: 'Cranberry margaritas became a standard holiday riff as bars looked for festive color without abandoning popular templates.',
    fun_fact_source: 'Modern holiday margarita menus',
    ingredients: '2 oz blanco tequila|1 oz cranberry juice|0.75 oz fresh lime juice|0.5 oz Cointreau',
    instructions: '1. Optional salt half-rim. 2. Shake all ingredients with ice. 3. Strain over fresh ice. 4. Garnish with a lime wheel.',
  },
  {
    slug: 'thanksgiving-punch',
    name: 'Thanksgiving Punch',
    short_description: 'A sharing punch of cognac or whiskey with apple cider, cranberry, and spice.',
    long_description: 'Thanksgiving Punch is a batchable fall holiday punch built from spirit, apple cider, cranberry, and citrus. Spice and fruit make it table-friendly for gatherings. Served over ice in a punch bowl or pitcher, it is designed for hosting rather than single-serve precision.',
    seo_description: 'Build Thanksgiving Punch with cognac, apple cider, cranberry, and spice for a holiday sharing drink.',
    base_spirit: 'Cognac', category_primary: 'Punch', categories_all: 'holiday|thanksgiving|punch|party|fall',
    tags: 'cognac|apple-cider|cranberry|punch|thanksgiving',
    image_alt: 'Thanksgiving Punch in a punch cup over ice, deep amber-red, orange peel.',
    glassware: 'Punch cup', garnish: 'orange peel|cinnamon stick', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 5, flavor_tartness: 4, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 4,
    notes: 'Batch and chill before guests arrive. Add sparkling wine or soda at service for lift if desired.',
    fun_fact: 'American Thanksgiving punches often combine cider and cranberry because both ingredients already define the holiday meal.',
    fun_fact_source: 'American holiday entertaining traditions',
    ingredients: '6 oz Cognac|8 oz apple cider|6 oz cranberry juice|2 oz fresh orange juice|1 oz simple syrup|2 dashes Angostura bitters|optional 4 oz sparkling wine',
    instructions: '1. Combine Cognac, cider, juices, syrup, and bitters in a pitcher with ice. 2. Stir to chill. 3. Serve in cups over ice. 4. Top with sparkling wine if using and garnish.',
  },
  {
    slug: 'wassail',
    name: 'Wassail',
    short_description: 'A hot spiced holiday punch of cider or ale with fruit and warm spice.',
    long_description: 'Wassail is a hot festive punch rooted in English winter celebration. Apple cider or ale is warmed with citrus, sugar, and spices, sometimes fortified with spirit. Served in mugs, it is communal and ceremonial rather than a precise cocktail template.',
    seo_description: 'Warm Wassail with apple cider, spice, and citrus for a classic holiday punch.',
    base_spirit: 'Wine', category_primary: 'Hot', categories_all: 'holiday|christmas|hot|punch|winter',
    tags: 'cider|spice|hot|wassail|christmas',
    image_alt: 'Wassail in a mug, amber, cinnamon stick, light steam.',
    glassware: 'Mug', garnish: 'cinnamon stick|orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 3, flavor_sweetness: 6, flavor_tartness: 2, flavor_bitterness: 1, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Keep below a boil. Fortify with brandy or sherry at the end if desired.',
    fun_fact: 'Wassailing refers both to the drink and to winter blessing rituals in English orchard and Christmas traditions.',
    fun_fact_source: 'English wassail and Christmas traditions',
    ingredients: '6 oz apple cider|1 oz brandy optional|0.5 oz honey|orange peel|2 cloves|1 cinnamon stick|pinch allspice',
    instructions: '1. Warm cider with honey and spices. 2. Add optional brandy in the mug. 3. Top with hot cider. 4. Garnish with cinnamon and orange peel.',
  },
  {
    slug: 'smoking-bishop',
    name: 'Smoking Bishop',
    short_description: 'A Victorian hot port punch with roasted oranges and spice.',
    long_description: 'Smoking Bishop is a hot port-and-citrus punch associated with Victorian Christmas literature and older English bishop punches. Oranges are roasted or studded with cloves, then combined with port and warm spice. Served hot, it is festive, aromatic, and historical.',
    seo_description: 'Make a Smoking Bishop with port, roasted orange, and spice for a classic Victorian holiday punch.',
    base_spirit: 'Wine', category_primary: 'Hot', categories_all: 'holiday|christmas|hot|punch|classic',
    tags: 'port|orange|spice|christmas|victorian',
    image_alt: 'Smoking Bishop in a mug, deep ruby, orange peel, light steam.',
    glassware: 'Mug', garnish: 'orange peel', technique: 'Build', difficulty: 'Intermediate',
    flavor_strength: 5, flavor_sweetness: 5, flavor_tartness: 2, flavor_bitterness: 2, flavor_aroma: 8, flavor_texture: 5,
    notes: 'Roast clove-studded oranges before combining with warmed port. Do not boil the port.',
    fun_fact: 'Smoking Bishop is famously referenced at the end of Charles Dickens’s A Christmas Carol as a reconciliatory Christmas drink.',
    fun_fact_source: 'Charles Dickens, A Christmas Carol; English bishop punch histories',
    ingredients: '4 oz ruby port|1 oz cognac optional|half roasted orange studded with cloves|0.5 oz sugar|1 cinnamon stick|pinch allspice',
    instructions: '1. Warm port with sugar and spices. 2. Add roasted clove-studded orange and optional cognac. 3. Steep briefly and strain into a mug. 4. Garnish with orange peel.',
  },
  {
    slug: 'black-velvet',
    name: 'Black Velvet',
    short_description: 'A layered sparkling mix of stout and Champagne for ceremonial occasions.',
    long_description: 'The Black Velvet combines equal parts stout and Champagne in a flute. The beer’s roasted bitterness meets sparkling wine’s acidity for a surprising, elegant two-ingredient drink. It is associated with mourning and celebration alike in cocktail lore and suits New Year’s or formal winter hosting.',
    seo_description: 'Build a Black Velvet with stout and Champagne for a classic ceremonial sparkling cocktail.',
    base_spirit: 'Wine', category_primary: 'Sparkling', categories_all: 'holiday|nye|sparkling|classic',
    tags: 'champagne|stout|sparkling|nye|layered',
    image_alt: 'Black Velvet in a Champagne flute, dark stout beneath pale sparkling wine.',
    glassware: 'Champagne flute', garnish: 'None', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 2, flavor_tartness: 2, flavor_bitterness: 4, flavor_aroma: 6, flavor_texture: 6,
    notes: 'Pour stout first, then Champagne gently to preserve a visual layer. Guinness is traditional.',
    fun_fact: 'The Black Velvet is said to have been created in 1861 to mourn Prince Albert, mixing black stout with Champagne.',
    fun_fact_source: 'Classic Champagne cocktail histories',
    ingredients: '3 oz chilled stout|3 oz chilled Champagne',
    instructions: '1. Pour stout into a chilled flute. 2. Slowly top with Champagne over a spoon if layering. 3. Serve ungarnished.',
  },
  {
    slug: 'irish-mule',
    name: 'Irish Mule',
    short_description: 'A mule highball made with Irish whiskey, lime, and ginger beer.',
    long_description: 'The Irish Mule swaps vodka for Irish whiskey in the classic mule template. Whiskey warmth sits under lime and spicy ginger beer for an easy St. Patrick’s Day and year-round highball. Served over ice, it is approachable and clearly themed without gimmick ingredients.',
    seo_description: 'Build an Irish Mule with Irish whiskey, lime, and ginger beer for a classic mule variation.',
    base_spirit: 'Whiskey', category_primary: 'Highball', categories_all: 'holiday|st-patricks|highball|mule-family',
    tags: 'irish-whiskey|lime|ginger-beer|mule|st-patricks',
    image_alt: 'Irish Mule in a highball or copper mug over ice, pale gold, lime wheel.',
    glassware: 'Highball glass', garnish: 'lime wheel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 4, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 4,
    notes: 'Use a spicy ginger beer. A soft Irish whiskey keeps the drink smooth.',
    fun_fact: 'Irish Mules are a straightforward spirit-swap on the Moscow Mule and a common St. Patrick’s Day special.',
    fun_fact_source: 'Modern mule variation menus',
    ingredients: '2 oz Irish whiskey|0.5 oz fresh lime juice|4 oz ginger beer',
    instructions: '1. Build whiskey and lime over ice. 2. Top with ginger beer and stir gently. 3. Garnish with a lime wheel.',
  },
  {
    slug: 'snowball',
    name: 'Snowball',
    short_description: 'A British holiday highball of Advocaat and lemonade, sometimes with lime.',
    long_description: 'The Snowball is a British Christmas highball built from Advocaat egg liqueur topped with lemonade. It is pale, creamy-yellow, and lightly festive. Lime cordial appears in many versions. Served over ice, it is simple party fare rather than a technical classic.',
    seo_description: 'Build a Snowball with Advocaat and lemonade for a classic British Christmas cocktail.',
    base_spirit: 'Liqueur', category_primary: 'Highball', categories_all: 'holiday|christmas|highball|british',
    tags: 'advocaat|lemonade|christmas|british',
    image_alt: 'Snowball in a highball over ice, pale yellow, ungarnished.',
    glassware: 'Highball glass', garnish: 'None', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 3, flavor_sweetness: 7, flavor_tartness: 2, flavor_bitterness: 0, flavor_aroma: 4, flavor_texture: 6,
    notes: 'Advocaat brands vary in thickness; shake briefly with ice if needed before topping with lemonade.',
    fun_fact: 'The Snowball became a mid-twentieth-century British Christmas party staple built around Advocaat.',
    fun_fact_source: 'British Christmas drink traditions',
    ingredients: '2 oz Advocaat|0.5 oz lime cordial optional|4 oz lemonade',
    instructions: '1. Add Advocaat and optional lime cordial to a highball with ice. 2. Top with lemonade. 3. Stir gently. 4. Serve ungarnished.',
  },
  {
    slug: 'black-magic',
    name: 'Black Magic',
    short_description: 'A dark Halloween coffee cocktail of vodka, coffee liqueur, and lime.',
    long_description: 'Black Magic is a short, dark vodka-and-coffee-liqueur drink sharpened with lime. The color and name make it a natural Halloween party cocktail, while the structure stays simple and drinkable. Served up or over ice, it is more restrained than novelty Halloween shots.',
    seo_description: 'Shake a Black Magic with vodka, coffee liqueur, and lime for a dark Halloween cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'holiday|halloween|dessert|party',
    tags: 'vodka|coffee-liqueur|lime|halloween',
    image_alt: 'Black Magic in a coupe, deep brown-black, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 5, flavor_tartness: 3, flavor_bitterness: 2, flavor_aroma: 6, flavor_texture: 5,
    notes: 'Lime should be noticeable enough to cut sweetness. Serve up for a cleaner Halloween presentation.',
    fun_fact: 'Black Magic appears on Halloween menus as a darker coffee-vodka alternative to sweet novelty shots.',
    fun_fact_source: 'American Halloween cocktail menus',
    ingredients: '1.5 oz vodka|1 oz coffee liqueur|0.5 oz fresh lime juice',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'bishop',
    name: 'Bishop',
    short_description: 'A classic port cocktail with roasted orange and warm spice, served hot or cold.',
    long_description: 'The Bishop is an older port-and-orange drink that precedes the Smoking Bishop elaboration. Port, citrus, and spice create a wine-based holiday cocktail that can be served warm. It is fruitier and simpler than many brandy desserts.',
    seo_description: 'Make a Bishop with port, orange, and spice for a classic holiday wine cocktail.',
    base_spirit: 'Wine', category_primary: 'Hot', categories_all: 'holiday|christmas|classic|wine',
    tags: 'port|orange|spice|christmas|classic',
    image_alt: 'Bishop in a mug or wine glass, deep ruby, orange peel.',
    glassware: 'Mug', garnish: 'orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 5, flavor_tartness: 2, flavor_bitterness: 2, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Warm gently with orange and cloves. Sugar only if the port is particularly dry.',
    fun_fact: 'Bishop punches are part of a family of English wine punches named for clerical titles, later inspiring Smoking Bishop.',
    fun_fact_source: 'English punch and bishop drink histories',
    ingredients: '4 oz ruby port|0.5 oz sugar optional|orange peel|3 cloves|pinch cinnamon',
    instructions: '1. Warm port with orange peel, cloves, cinnamon, and optional sugar. 2. Do not boil. 3. Strain into a mug. 4. Garnish with orange peel.',
  },
  {
    slug: 'apple-cider-punch',
    name: 'Apple Cider Punch',
    short_description: 'A fall holiday sharing punch of cider, brandy, citrus, and spice.',
    long_description: 'Apple Cider Punch is a host-friendly batch drink for Thanksgiving and autumn holidays. Hard or sweet cider is fortified with brandy and brightened with citrus and spice. Served from a pitcher or bowl over ice, it scales easily for a crowd.',
    seo_description: 'Build Apple Cider Punch with cider, brandy, citrus, and spice for a holiday sharing cocktail.',
    base_spirit: 'Brandy', category_primary: 'Punch', categories_all: 'holiday|thanksgiving|punch|fall|party',
    tags: 'apple-cider|brandy|punch|thanksgiving|spice',
    image_alt: 'Apple Cider Punch in a punch cup over ice, golden amber, cinnamon stick.',
    glassware: 'Punch cup', garnish: 'cinnamon stick|orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 5, flavor_tartness: 3, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 4,
    notes: 'For a lighter punch use sweet cider; for a drier adult punch use hard cider and less syrup.',
    fun_fact: 'Cider punches are a practical American hosting tradition whenever autumn cider is abundant.',
    fun_fact_source: 'American fall entertaining traditions',
    ingredients: '8 oz apple cider|4 oz brandy|2 oz fresh orange juice|1 oz fresh lemon juice|1 oz simple syrup|2 dashes Angostura bitters|optional 4 oz ginger ale',
    instructions: '1. Combine cider, brandy, juices, syrup, and bitters in a pitcher with ice. 2. Stir to chill. 3. Top with ginger ale if using. 4. Serve in cups with cinnamon and orange peel.',
  },
  {
    slug: 'peppermint-white-russian',
    name: 'Peppermint White Russian',
    short_description: 'A White Russian variation finished with peppermint for Christmas service.',
    long_description: 'The Peppermint White Russian keeps vodka, coffee liqueur, and cream, then adds peppermint schnapps for a holiday accent. Served over ice, it remains a dessert highball with a clear Christmas mint note. Peppermint should stay secondary to coffee and cream.',
    seo_description: 'Build a Peppermint White Russian with vodka, coffee liqueur, cream, and peppermint for a holiday cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'holiday|christmas|dessert|coffee',
    tags: 'vodka|coffee-liqueur|cream|peppermint|christmas',
    image_alt: 'Peppermint White Russian in a rocks glass over ice, layered cream over coffee-brown.',
    glassware: 'Rocks glass', garnish: 'None', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 6, flavor_tartness: 0, flavor_bitterness: 2, flavor_aroma: 7, flavor_texture: 8,
    notes: 'Add peppermint sparingly. Float cream or stir fully depending on preferred look.',
    fun_fact: 'Peppermint White Russians are a common Christmas riff on the standard White Russian dessert highball.',
    fun_fact_source: 'Modern holiday cocktail menus',
    ingredients: '1.5 oz vodka|1 oz coffee liqueur|0.5 oz peppermint schnapps|1 oz heavy cream',
    instructions: '1. Build vodka, coffee liqueur, and peppermint over ice. 2. Float or stir in cream. 3. Serve ungarnished.',
  },
];

function csvEscape(v: string | number) {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main() {
  const headers = ['ID','slug','name','short_description','long_description','seo_description','base_spirit','category_primary','categories_all','tags','image_url','image_alt','glassware','garnish','technique','difficulty','flavor_strength','flavor_sweetness','flavor_tartness','flavor_bitterness','flavor_aroma','flavor_texture','notes','fun_fact','fun_fact_source','metadata_json','ingredients','instructions'];
  const rows = drafts.map((d, i) => [`mw_review_004_${String(i+1).padStart(3,'0')}`, d.slug, d.name, d.short_description, d.long_description, d.seo_description, d.base_spirit, d.category_primary, d.categories_all, d.tags, '', d.image_alt, d.glassware, d.garnish, d.technique, d.difficulty, d.flavor_strength, d.flavor_sweetness, d.flavor_tartness, d.flavor_bitterness, d.flavor_aroma, d.flavor_texture, d.notes, d.fun_fact, d.fun_fact_source, '{}', d.ingredients, d.instructions].map(csvEscape).join(','));
  const out = path.join(process.cwd(), 'data', 'review-batch-004.csv');
  fs.writeFileSync(out, [headers.join(','), ...rows].join('\n') + '\n');
  console.log(`Wrote ${drafts.length} → ${out}\n` + drafts.map(d => d.slug).join('\n'));
}
main();
