#!/usr/bin/env tsx
/** review-batch-005: modern craft anchors + mezcal/agave depth */
import * as fs from 'fs';
import * as path from 'path';

type Draft = {
  slug: string; name: string; short_description: string; long_description: string; seo_description: string;
  base_spirit: string; category_primary: string; categories_all: string; tags: string; image_alt: string;
  glassware: string; garnish: string; technique: 'Shake' | 'Stir' | 'Build' | 'Blend' | 'Swizzle';
  difficulty: 'Easy' | 'Intermediate' | 'Advanced';
  flavor_strength: number; flavor_sweetness: number; flavor_tartness: number; flavor_bitterness: number;
  flavor_aroma: number; flavor_texture: number;
  notes: string; fun_fact: string; fun_fact_source: string; ingredients: string; instructions: string;
};

const drafts: Draft[] = [
  // --- Modern craft anchors ---
  {
    slug: 'gin-basil-smash',
    name: 'Gin Basil Smash',
    short_description: 'A muddled gin sour with fresh basil, lemon, and sugar for a bright herbal profile.',
    long_description: 'The Gin Basil Smash muddles fresh basil into a gin-lemon-sugar sour. Basil oils perfume the drink while lemon keeps it sharp and refreshing. Shaken and served over ice, it became a defining modern craft highball-adjacent sour. Fresh basil is non-negotiable.',
    seo_description: 'Shake a Gin Basil Smash with gin, fresh basil, lemon, and sugar for a modern herbal sour.',
    base_spirit: 'Gin', category_primary: 'Sour', categories_all: 'modern-classic|sour|gin|herbal',
    tags: 'gin|basil|lemon|muddled|modern',
    image_alt: 'Gin Basil Smash in a rocks glass over ice, pale green tint, basil sprig.',
    glassware: 'Rocks glass', garnish: 'basil sprig', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Muddle basil gently to release oils without shredding into bitterness. Use plenty of fresh leaves.',
    fun_fact: 'Joerg Meyer created the Gin Basil Smash at Hamburg’s Le Lion, and it quickly became an international modern classic.',
    fun_fact_source: 'Le Lion / Joerg Meyer cocktail histories',
    ingredients: '2 oz gin|1 oz fresh lemon juice|0.75 oz simple syrup|10-12 fresh basil leaves',
    instructions: '1. Gently muddle basil with syrup in a shaker. 2. Add gin and lemon; shake with ice. 3. Fine-strain into a rocks glass over ice. 4. Garnish with a basil sprig.',
  },
  {
    slug: 'chartreuse-swizzle',
    name: 'Chartreuse Swizzle',
    short_description: 'A green Chartreuse swizzle with pineapple, lime, and falernum over crushed ice.',
    long_description: 'The Chartreuse Swizzle builds a tall crushed-ice drink around green Chartreuse, pineapple, lime, and falernum. Herbal intensity meets tropical sweetness in a swizzle format. It is a modern craft staple that showcases Chartreuse outside stirred spirit-forward drinks.',
    seo_description: 'Swizzle a Chartreuse Swizzle with green Chartreuse, pineapple, lime, and falernum over crushed ice.',
    base_spirit: 'Liqueur', category_primary: 'Swizzle', categories_all: 'modern-classic|swizzle|tiki|herbal',
    tags: 'chartreuse|pineapple|lime|falernum|swizzle',
    image_alt: 'Chartreuse Swizzle in a tall glass over crushed ice, green-gold, mint garnish.',
    glassware: 'Highball glass', garnish: 'mint sprig', technique: 'Swizzle', difficulty: 'Intermediate',
    flavor_strength: 7, flavor_sweetness: 5, flavor_tartness: 5, flavor_bitterness: 2, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Swizzle with crushed ice until the glass frosts. Green Chartreuse dominates—measure precisely.',
    fun_fact: 'The Chartreuse Swizzle is widely credited to Marco Dionysos and helped popularize Chartreuse in modern tiki-leaning craft bars.',
    fun_fact_source: 'Modern craft and tiki cocktail histories',
    ingredients: '1.5 oz green Chartreuse|1 oz pineapple juice|0.75 oz fresh lime juice|0.5 oz falernum',
    instructions: '1. Add all ingredients to a tall glass. 2. Fill with crushed ice and swizzle until frosty. 3. Top with more crushed ice. 4. Garnish with mint.',
  },
  {
    slug: 'final-word',
    name: 'Final Word',
    short_description: 'A Last Word variation that swaps gin for rye whiskey.',
    long_description: 'The Final Word keeps the equal-parts Last Word structure—green Chartreuse, maraschino, and lime—but uses rye instead of gin. Whiskey warmth shifts the herbal sour toward a richer, spicier finish. Shaken and served up, it is a clear modern variation for whiskey drinkers.',
    seo_description: 'Shake a Final Word with rye, green Chartreuse, maraschino, and lime for a Last Word variation.',
    base_spirit: 'Rye', category_primary: 'Sour', categories_all: 'modern-classic|sour|last-word-family|whiskey',
    tags: 'rye|chartreuse|maraschino|lime|equal-parts',
    image_alt: 'Final Word in a coupe, pale green-gold, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 7, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 2, flavor_aroma: 8, flavor_texture: 5,
    notes: 'Equal parts are essential. A spicy rye stands up to Chartreuse better than a soft bourbon.',
    fun_fact: 'The Final Word is part of the wave of Last Word riffs that followed the drink’s early-2000s craft revival.',
    fun_fact_source: 'Modern Last Word variation histories',
    ingredients: '0.75 oz rye whiskey|0.75 oz green Chartreuse|0.75 oz maraschino liqueur|0.75 oz fresh lime juice',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'trade-winds',
    name: 'Trade Winds',
    short_description: 'A mid-century tiki sour with rum, apricot brandy, lemon, and orgeat.',
    long_description: 'The Trade Winds is a tropical sour associated with mid-century tiki service: rum, apricot brandy, lemon, and orgeat, often frothed with egg white. Apricot and almond soften the citrus while rum keeps the structure. Served up or over ice, it is a craft-tiki bridge drink.',
    seo_description: 'Shake a Trade Winds with rum, apricot brandy, lemon, and orgeat for a classic tiki sour.',
    base_spirit: 'Rum', category_primary: 'Tiki', categories_all: 'modern-classic|tiki|sour|tropical',
    tags: 'rum|apricot|orgeat|lemon|tiki',
    image_alt: 'Trade Winds in a coupe, pale gold with soft foam, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 6, flavor_sweetness: 5, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 7,
    notes: 'Dry-shake if using egg white. Orgeat quality strongly affects the finish.',
    fun_fact: 'Trade Winds appears in mid-century tropical bar manuals and later craft-tiki revivals as an apricot-forward rum sour.',
    fun_fact_source: 'Mid-century tiki manuals; modern tiki revivals',
    ingredients: '1 oz white rum|1 oz dark rum|0.5 oz apricot brandy|1 oz fresh lemon juice|0.5 oz orgeat|1 egg white optional',
    instructions: '1. Dry-shake if using egg white. 2. Add ice and shake again. 3. Fine-strain into a chilled coupe. 4. Serve ungarnished.',
  },
  {
    slug: 'test-pilot',
    name: 'Test Pilot',
    short_description: 'A Donn Beach tiki drink with rum, lime, falernum, Cointreau, and bitters.',
    long_description: 'The Test Pilot is a compact Donn Beach tiki sour built on rum with lime, falernum, Cointreau, and bitters. It is shorter and denser than a Mai Tai, with spice and orange over citrus. Served over crushed or cubed ice, it rewards precise measures.',
    seo_description: 'Shake a Test Pilot with rum, lime, falernum, and Cointreau for a classic Donn Beach tiki cocktail.',
    base_spirit: 'Rum', category_primary: 'Tiki', categories_all: 'classic|tiki|sour|donn-beach',
    tags: 'rum|falernum|lime|cointreau|tiki',
    image_alt: 'Test Pilot in a rocks glass over crushed ice, amber, mint sprig.',
    glassware: 'Rocks glass', garnish: 'mint sprig', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 7, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 2, flavor_aroma: 8, flavor_texture: 5,
    notes: 'A blend of light and dark or Jamaican rum works well. Keep falernum measured—sweetness climbs fast.',
    fun_fact: 'The Test Pilot is one of Donn Beach’s mid-century tiki formulas later reconstructed by tiki historians.',
    fun_fact_source: 'Jeff Berry tiki research; Don the Beachcomber histories',
    ingredients: '1.5 oz dark rum|0.75 oz light rum|0.5 oz fresh lime juice|0.5 oz falernum|0.5 oz Cointreau|1 dash Angostura bitters',
    instructions: '1. Shake all ingredients with ice. 2. Strain into a rocks glass over crushed ice. 3. Garnish with mint.',
  },
  {
    slug: 'three-dots-and-a-dash',
    name: 'Three Dots and a Dash',
    short_description: 'A rum tiki classic with falernum, allspice, citrus, and honey, named in Morse code.',
    long_description: 'Three Dots and a Dash is a Donn Beach rum drink whose name means “V” for victory in Morse code. Multiple rums meet falernum, allspice dram, citrus, and honey in a crushed-ice build. It is aromatic, spiced, and central to serious tiki menus.',
    seo_description: 'Shake Three Dots and a Dash with rum, falernum, allspice, and citrus for a classic Donn Beach tiki cocktail.',
    base_spirit: 'Rum', category_primary: 'Tiki', categories_all: 'classic|tiki|rum|donn-beach',
    tags: 'rum|falernum|allspice|honey|tiki',
    image_alt: 'Three Dots and a Dash in a footed tiki or rocks glass over crushed ice, amber, pineapple and cherry.',
    glassware: 'Rocks glass', garnish: 'pineapple fronds|cherries', technique: 'Shake', difficulty: 'Advanced',
    flavor_strength: 7, flavor_sweetness: 5, flavor_tartness: 5, flavor_bitterness: 2, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Use a mix of aged and Jamaican rum if possible. Allspice dram is potent—do not overpour.',
    fun_fact: 'Donn Beach created Three Dots and a Dash during World War II; the Morse-code name signals “V” for victory.',
    fun_fact_source: 'Jeff Berry; Don the Beachcomber histories',
    ingredients: '1.5 oz aged rum|0.5 oz Jamaican rum|0.5 oz fresh lime juice|0.5 oz fresh orange juice|0.5 oz honey syrup|0.25 oz falernum|0.25 oz allspice dram|1 dash Angostura bitters',
    instructions: '1. Shake all ingredients with ice. 2. Strain into a glass filled with crushed ice. 3. Garnish with pineapple and cherries.',
  },

  // --- Mezcal / agave depth ---
  {
    slug: 'mezcal-margarita',
    name: 'Mezcal Margarita',
    short_description: 'A margarita built on mezcal for a smoky agave-lime profile.',
    long_description: 'The Mezcal Margarita keeps lime and orange liqueur but replaces tequila with mezcal. Smoke and earth sit under citrus, making the drink drier and more savory than a standard margarita. Served on the rocks, it is the clearest entry point from tequila to mezcal.',
    seo_description: 'Shake a Mezcal Margarita with mezcal, lime, and orange liqueur for a smoky margarita variation.',
    base_spirit: 'Mezcal', category_primary: 'Sour', categories_all: 'modern|sour|margarita-family|mezcal|agave',
    tags: 'mezcal|lime|cointreau|margarita|smoke',
    image_alt: 'Mezcal Margarita in a rocks glass over ice, pale, lime wheel, optional salt rim.',
    glassware: 'Rocks glass', garnish: 'lime wheel|optional salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 7, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 8, flavor_texture: 5,
    notes: 'Espadín mezcal keeps it approachable. Half salt rim only—smoke already adds intensity.',
    fun_fact: 'Mezcal margaritas became a standard craft-bar agave call as mezcal distribution widened in the 2010s.',
    fun_fact_source: 'Modern agave cocktail practice',
    ingredients: '2 oz mezcal|1 oz fresh lime juice|0.75 oz Cointreau|optional salt rim',
    instructions: '1. Optional salt half-rim. 2. Shake mezcal, lime, and Cointreau with ice. 3. Strain over fresh ice. 4. Garnish with lime.',
  },
  {
    slug: 'mezcal-last-word',
    name: 'Mezcal Last Word',
    short_description: 'An equal-parts Last Word with mezcal in place of gin.',
    long_description: 'The Mezcal Last Word preserves Chartreuse, maraschino, and lime in equal parts, swapping gin for mezcal. Smoke threads through the herbal sour and deepens the finish. Shaken and served up, it is one of the most popular Last Word riffs.',
    seo_description: 'Shake a Mezcal Last Word with mezcal, green Chartreuse, maraschino, and lime.',
    base_spirit: 'Mezcal', category_primary: 'Sour', categories_all: 'modern-classic|sour|last-word-family|mezcal',
    tags: 'mezcal|chartreuse|maraschino|lime|equal-parts',
    image_alt: 'Mezcal Last Word in a coupe, pale green, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 7, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 2, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Equal parts are mandatory. A clean espadín works better than a heavily peated outlier mezcal.',
    fun_fact: 'Mezcal Last Words spread quickly after the Last Word revival as bars looked for smoky equal-parts variations.',
    fun_fact_source: 'Modern Last Word riff histories',
    ingredients: '0.75 oz mezcal|0.75 oz green Chartreuse|0.75 oz maraschino liqueur|0.75 oz fresh lime juice',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'mezcal-sour',
    name: 'Mezcal Sour',
    short_description: 'A straightforward mezcal whiskey-sour template with lime or lemon and egg white optional.',
    long_description: 'The Mezcal Sour applies the classic sour template to mezcal: spirit, citrus, sugar, and optional egg white. Smoke replaces whiskey’s oak as the defining mid-palate note. Served up or over ice, it is a clean way to taste mezcal in a familiar structure.',
    seo_description: 'Shake a Mezcal Sour with mezcal, citrus, and sugar for a smoky classic-style sour.',
    base_spirit: 'Mezcal', category_primary: 'Sour', categories_all: 'modern|sour|mezcal|agave',
    tags: 'mezcal|lime|sour|egg-white|smoke',
    image_alt: 'Mezcal Sour in a coupe, pale with soft foam, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 7, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 8, flavor_texture: 7,
    notes: 'Lime is traditional with agave; lemon works for a softer profile. Dry-shake if using egg white.',
    fun_fact: 'Simple mezcal sours helped introduce mezcal to drinkers already comfortable with whiskey sour structure.',
    fun_fact_source: 'Modern agave bar education practice',
    ingredients: '2 oz mezcal|1 oz fresh lime juice|0.75 oz simple syrup|1 egg white optional',
    instructions: '1. Dry-shake if using egg white. 2. Add ice and shake again. 3. Fine-strain into a chilled coupe. 4. Serve ungarnished.',
  },
  {
    slug: 'illegal',
    name: 'Illegal',
    short_description: 'A mezcal and Jamaican rum sour with falernum, lime, and maraschino.',
    long_description: 'Illegal combines mezcal and funky Jamaican rum with falernum, lime, and maraschino. Smoke, overripe fruit, and spice make it denser than a margarita and more complex than a basic mezcal sour. Shaken and served up, it is a modern agave-tiki crossover.',
    seo_description: 'Shake an Illegal with mezcal, Jamaican rum, falernum, lime, and maraschino.',
    base_spirit: 'Mezcal', category_primary: 'Sour', categories_all: 'modern-classic|sour|mezcal|tiki',
    tags: 'mezcal|jamaican-rum|falernum|lime|maraschino',
    image_alt: 'Illegal in a coupe, pale gold, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 8, flavor_sweetness: 4, flavor_tartness: 6, flavor_bitterness: 2, flavor_aroma: 9, flavor_texture: 5,
    notes: 'A funky Jamaican rum is important to the drink’s identity. Keep falernum and maraschino measured.',
    fun_fact: 'Illegal was created by Enrico Collivasone and later popularized through modern craft and Death & Co circles as a mezcal-rum hybrid sour.',
    fun_fact_source: 'Modern craft cocktail attributions; Death & Co era menus',
    ingredients: '1 oz mezcal|0.75 oz Jamaican rum|0.75 oz fresh lime juice|0.5 oz falernum|0.25 oz maraschino liqueur|1 egg white optional',
    instructions: '1. Dry-shake if using egg white. 2. Add ice and shake hard. 3. Fine-strain into a chilled coupe. 4. Serve ungarnished.',
  },
  {
    slug: 'anejo-old-fashioned',
    name: 'Añejo Old Fashioned',
    short_description: 'An Old Fashioned built on añejo tequila with agave and bitters.',
    long_description: 'The Añejo Old Fashioned treats aged tequila like whiskey: spirit, agave syrup, and bitters over a large cube. Oak and caramel from añejo replace bourbon’s grain sweetness while staying clearly agave. It is a spirit-forward counterpoint to fruit-heavy margarita variants.',
    seo_description: 'Stir an Añejo Old Fashioned with añejo tequila, agave syrup, and bitters.',
    base_spirit: 'Tequila', category_primary: 'Spirit-Forward', categories_all: 'modern|spirit-forward|old-fashioned-family|agave',
    tags: 'anejo|tequila|agave|bitters|stirred',
    image_alt: 'Añejo Old Fashioned in a rocks glass over a large ice cube, deep gold, orange peel.',
    glassware: 'Rocks glass', garnish: 'orange peel', technique: 'Stir', difficulty: 'Easy',
    flavor_strength: 8, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 4, flavor_aroma: 7, flavor_texture: 6,
    notes: 'Use true 100% agave añejo. Agave syrup should be light—tequila already carries sweetness.',
    fun_fact: 'Tequila Old Fashioneds, especially with añejo, became a craft-bar staple as drinkers sought spirit-forward agave options beyond margaritas.',
    fun_fact_source: 'Modern agave cocktail practice',
    ingredients: '2 oz añejo tequila|0.25 oz agave syrup|2 dashes Angostura bitters|1 dash orange bitters',
    instructions: '1. Stir tequila, agave, and bitters with ice. 2. Strain over a large ice cube. 3. Garnish with an expressed orange peel.',
  },
  {
    slug: 'blanco-margarita',
    name: 'Blanco Margarita',
    short_description: 'A margarita specified with blanco tequila for a clean, bright agave profile.',
    long_description: 'The Blanco Margarita is the unaged expression of the classic template. Blanco tequila keeps agave character vivid under lime and orange liqueur. Specifying blanco helps home bartenders compare tequila styles against reposado and añejo builds.',
    seo_description: 'Shake a Blanco Margarita with blanco tequila, lime, and orange liqueur for a clean classic margarita.',
    base_spirit: 'Tequila', category_primary: 'Sour', categories_all: 'classic|sour|margarita-family|agave',
    tags: 'blanco|tequila|lime|cointreau|margarita',
    image_alt: 'Blanco Margarita in a coupe, pale green, optional salt rim, lime wheel.',
    glassware: 'Coupe', garnish: 'lime wheel|optional salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 7, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 5,
    notes: '100% agave blanco only. A half salt rim is enough.',
    fun_fact: 'Calling out blanco distinguishes bright agave margaritas from oak-influenced reposado and añejo versions.',
    fun_fact_source: 'Modern tequila style guides',
    ingredients: '2 oz blanco tequila|1 oz fresh lime juice|0.75 oz Cointreau|optional salt rim',
    instructions: '1. Optional salt half-rim. 2. Shake tequila, lime, and Cointreau with ice. 3. Fine-strain into a chilled coupe or over ice. 4. Garnish with lime.',
  },
  {
    slug: 'reposado-margarita',
    name: 'Reposado Margarita',
    short_description: 'A margarita made with reposado tequila for light oak and warmer agave.',
    long_description: 'The Reposado Margarita keeps the classic lime and orange-liqueur balance while using lightly aged tequila. Oak and vanilla soften the edges without burying agave. It sits between blanco brightness and añejo richness.',
    seo_description: 'Shake a Reposado Margarita with reposado tequila, lime, and orange liqueur.',
    base_spirit: 'Tequila', category_primary: 'Sour', categories_all: 'classic|sour|margarita-family|agave',
    tags: 'reposado|tequila|lime|cointreau|margarita',
    image_alt: 'Reposado Margarita in a rocks glass over ice, pale gold, lime wheel.',
    glassware: 'Rocks glass', garnish: 'lime wheel|optional salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Choose a reposado with restrained oak so the drink stays a margarita, not an Old Fashioned with lime.',
    fun_fact: 'Reposado margaritas became popular as drinkers sought slightly richer agave character without moving fully to sipping añejo serves.',
    fun_fact_source: 'Modern margarita style practice',
    ingredients: '2 oz reposado tequila|1 oz fresh lime juice|0.75 oz Cointreau|optional salt rim',
    instructions: '1. Optional salt half-rim. 2. Shake all ingredients with ice. 3. Strain over fresh ice. 4. Garnish with lime.',
  },
  {
    slug: 'mezcal-martinez',
    name: 'Mezcal Martinez',
    short_description: 'A Martinez variation using mezcal with sweet vermouth, maraschino, and bitters.',
    long_description: 'The Mezcal Martinez applies the gin Martinez template to mezcal: sweet vermouth, maraschino, and bitters around a smoky base. It is stirred and spirit-forward, bridging classic vermouth drinks and modern agave culture.',
    seo_description: 'Stir a Mezcal Martinez with mezcal, sweet vermouth, maraschino, and bitters.',
    base_spirit: 'Mezcal', category_primary: 'Spirit-Forward', categories_all: 'modern|spirit-forward|martinez-family|mezcal',
    tags: 'mezcal|vermouth|maraschino|bitters|stirred',
    image_alt: 'Mezcal Martinez in a coupe, amber, orange peel.',
    glassware: 'Coupe', garnish: 'orange peel', technique: 'Stir', difficulty: 'Intermediate',
    flavor_strength: 8, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 4, flavor_aroma: 8, flavor_texture: 6,
    notes: 'Keep maraschino light. A softer mezcal lets vermouth show; a louder mezcal makes a smoke-forward Martinez.',
    fun_fact: 'Mezcal Martinez riffs followed the broader craft habit of translating gin classics onto agave bases.',
    fun_fact_source: 'Modern craft agave variation practice',
    ingredients: '1.5 oz mezcal|1.5 oz sweet vermouth|0.25 oz maraschino liqueur|2 dashes orange bitters',
    instructions: '1. Stir all ingredients with ice. 2. Strain into a chilled coupe. 3. Garnish with an orange peel.',
  },
  {
    slug: 'mezcal-manhattan',
    name: 'Mezcal Manhattan',
    short_description: 'A Manhattan variation with mezcal, sweet vermouth, and bitters.',
    long_description: 'The Mezcal Manhattan keeps vermouth and bitters while replacing whiskey with mezcal. Smoke and agave redefine the mid-palate without abandoning Manhattan architecture. Stirred and served up, it is a direct comparison drink for whiskey loyalists exploring mezcal.',
    seo_description: 'Stir a Mezcal Manhattan with mezcal, sweet vermouth, and bitters for a smoky Manhattan variation.',
    base_spirit: 'Mezcal', category_primary: 'Spirit-Forward', categories_all: 'modern|spirit-forward|manhattan-family|mezcal',
    tags: 'mezcal|vermouth|bitters|stirred|manhattan',
    image_alt: 'Mezcal Manhattan in a coupe, amber-brown, cherry garnish.',
    glassware: 'Coupe', garnish: 'brandied cherry', technique: 'Stir', difficulty: 'Easy',
    flavor_strength: 8, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 4, flavor_aroma: 8, flavor_texture: 6,
    notes: 'A 2:1 mezcal-to-vermouth ratio stays structured. Choose vermouth that can stand up to smoke.',
    fun_fact: 'Mezcal Manhattans became a shorthand way for bars to offer spirit-forward agave drinks to Manhattan drinkers.',
    fun_fact_source: 'Modern craft bar menus',
    ingredients: '2 oz mezcal|1 oz sweet vermouth|2 dashes Angostura bitters',
    instructions: '1. Stir all ingredients with ice. 2. Strain into a chilled coupe. 3. Garnish with a brandied cherry.',
  },
  {
    slug: 'spicy-margarita',
    name: 'Spicy Margarita',
    short_description: 'A margarita infused with fresh chili heat alongside tequila, lime, and orange liqueur.',
    long_description: 'The Spicy Margarita builds heat into the classic margarita using muddled or infused chili. Tequila, lime, and orange liqueur remain the frame; spice is the modifier. Served on the rocks, it is one of the most requested modern agave variations.',
    seo_description: 'Shake a Spicy Margarita with tequila, chili, lime, and orange liqueur for a hot-and-bright classic.',
    base_spirit: 'Tequila', category_primary: 'Sour', categories_all: 'modern|sour|margarita-family|agave|spicy',
    tags: 'tequila|chili|lime|spicy|margarita',
    image_alt: 'Spicy Margarita in a rocks glass over ice, pale, lime wheel, optional chili salt rim.',
    glassware: 'Rocks glass', garnish: 'lime wheel|optional chili salt rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 3, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Start with one jalapeño slice; heat climbs fast. Remove seeds for milder spice.',
    fun_fact: 'Spicy margaritas became a defining 2010s brunch and craft-bar call, second only to the classic in many agave programs.',
    fun_fact_source: 'Modern margarita menu trends',
    ingredients: '2 oz blanco tequila|1 oz fresh lime juice|0.75 oz Cointreau|2 slices jalapeño|optional chili salt rim',
    instructions: '1. Muddle jalapeño lightly in a shaker. 2. Add tequila, lime, and Cointreau; shake with ice. 3. Fine-strain over fresh ice. 4. Garnish with lime.',
  },
  {
    slug: 'agave-spritz',
    name: 'Agave Spritz',
    short_description: 'A light sparkling highball with tequila or mezcal, aperitivo, and soda.',
    long_description: 'The Agave Spritz stretches tequila or mezcal with bitter aperitivo and sparkling water or Prosecco. It is lower-intensity than a margarita and suited to daytime hosting. Smoke is optional depending on whether mezcal or tequila leads.',
    seo_description: 'Build an Agave Spritz with tequila, aperitivo, and sparkling wine or soda for a light agave highball.',
    base_spirit: 'Tequila', category_primary: 'Spritz', categories_all: 'modern|spritz|agave|aperitivo',
    tags: 'tequila|aperol|prosecco|spritz|agave',
    image_alt: 'Agave Spritz in a wine glass over ice, orange-pink, orange peel.',
    glassware: 'Wine glass', garnish: 'orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 4, flavor_tartness: 2, flavor_bitterness: 4, flavor_aroma: 6, flavor_texture: 4,
    notes: 'Blanco tequila keeps it bright; a splash of mezcal can add smoke without taking over.',
    fun_fact: 'Agave spritzes followed the spritz boom as bars looked for lighter tequila serves beyond margaritas and palomas.',
    fun_fact_source: 'Modern spritz and agave menu practice',
    ingredients: '1 oz blanco tequila|1 oz Aperol|3 oz Prosecco|1 oz club soda',
    instructions: '1. Fill a wine glass with ice. 2. Add tequila and Aperol. 3. Top with Prosecco and soda. 4. Garnish with an orange peel.',
  },
  {
    slug: 'smoke-signal',
    name: 'Smoke Signal',
    short_description: 'A mezcal highball with grapefruit and soda for a smoky, sessionable serve.',
    long_description: 'Smoke Signal is a simple mezcal-and-grapefruit highball lengthened with soda. It sits beside the Paloma but usually skips sweet grapefruit soda in favor of juice plus soda for a drier finish. Served tall, it is an easy mezcal weeknight drink.',
    seo_description: 'Build a Smoke Signal with mezcal, grapefruit juice, and soda for a smoky highball.',
    base_spirit: 'Mezcal', category_primary: 'Highball', categories_all: 'modern|highball|mezcal|agave',
    tags: 'mezcal|grapefruit|soda|highball|smoke',
    image_alt: 'Smoke Signal in a highball over ice, pale pink, grapefruit peel.',
    glassware: 'Highball glass', garnish: 'grapefruit peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 2, flavor_tartness: 5, flavor_bitterness: 2, flavor_aroma: 8, flavor_texture: 4,
    notes: 'Fresh grapefruit juice plus soda stays drier than bottled grapefruit soda. Adjust sweetness with a teaspoon of agave if needed.',
    fun_fact: 'Dry mezcal-and-grapefruit highballs proliferated as bars looked for Paloma alternatives with less sweetness and more smoke.',
    fun_fact_source: 'Modern mezcal highball menus',
    ingredients: '2 oz mezcal|1.5 oz fresh grapefruit juice|0.25 oz agave syrup optional|3 oz club soda',
    instructions: '1. Build mezcal, grapefruit, and optional agave over ice. 2. Top with soda and stir gently. 3. Garnish with grapefruit peel.',
  },
];

function csvEscape(v: string | number) {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main() {
  const headers = ['ID','slug','name','short_description','long_description','seo_description','base_spirit','category_primary','categories_all','tags','image_url','image_alt','glassware','garnish','technique','difficulty','flavor_strength','flavor_sweetness','flavor_tartness','flavor_bitterness','flavor_aroma','flavor_texture','notes','fun_fact','fun_fact_source','metadata_json','ingredients','instructions'];
  const rows = drafts.map((d,i)=>[`mw_review_005_${String(i+1).padStart(3,'0')}`,d.slug,d.name,d.short_description,d.long_description,d.seo_description,d.base_spirit,d.category_primary,d.categories_all,d.tags,'',d.image_alt,d.glassware,d.garnish,d.technique,d.difficulty,d.flavor_strength,d.flavor_sweetness,d.flavor_tartness,d.flavor_bitterness,d.flavor_aroma,d.flavor_texture,d.notes,d.fun_fact,d.fun_fact_source,'{}',d.ingredients,d.instructions].map(csvEscape).join(','));
  const out = path.join(process.cwd(),'data','review-batch-005.csv');
  fs.writeFileSync(out, [headers.join(','), ...rows].join('\n')+'\n');
  console.log(`Wrote ${drafts.length} → ${out}`);
  console.log(drafts.map(d=>d.slug).join('\n'));
}
main();
