#!/usr/bin/env tsx
/**
 * review-batch-007: gap fill — flips/fizzes/cobblers, pisco/cachaça,
 * punch quality, Irish/aperitivo depth, brunch + zero-proof demand.
 */
import * as fs from 'fs';
import * as path from 'path';

type Draft = {
  slug: string;
  name: string;
  short_description: string;
  long_description: string;
  seo_description: string;
  base_spirit: string;
  category_primary: string;
  categories_all: string;
  tags: string;
  image_alt: string;
  glassware: string;
  garnish: string;
  technique: 'Shake' | 'Stir' | 'Build' | 'Blend' | 'Swizzle';
  difficulty: 'Easy' | 'Intermediate' | 'Advanced';
  flavor_strength: number;
  flavor_sweetness: number;
  flavor_tartness: number;
  flavor_bitterness: number;
  flavor_aroma: number;
  flavor_texture: number;
  notes: string;
  fun_fact: string;
  fun_fact_source: string;
  ingredients: string;
  instructions: string;
};

const drafts: Draft[] = [
  {
    slug: 'alexander',
    name: 'Alexander',
    short_description: 'A classic cream cocktail of gin, crème de cacao, and cream, dusted with nutmeg.',
    long_description:
      'The Alexander is the gin original behind the better-known Brandy Alexander: equal parts gin, dark crème de cacao, and cream, shaken cold and finished with nutmeg. Chocolate and dairy soften the botanical gin without turning the drink into dessert syrup. Served up, it is a foundational cream classic.',
    seo_description: 'Shake an Alexander with gin, crème de cacao, and cream for the classic cream cocktail.',
    base_spirit: 'Gin',
    category_primary: 'Dessert',
    categories_all: 'classic|dessert|cream|gin|iba',
    tags: 'gin|creme-de-cacao|cream|nutmeg|dessert|classic',
    image_alt: 'Alexander in a coupe, opaque pale cocoa cream, light nutmeg dust.',
    glassware: 'Coupe',
    garnish: 'freshly grated nutmeg',
    technique: 'Shake',
    difficulty: 'Easy',
    flavor_strength: 5,
    flavor_sweetness: 7,
    flavor_tartness: 0,
    flavor_bitterness: 1,
    flavor_aroma: 6,
    flavor_texture: 8,
    notes: 'Dark crème de cacao reads richer than white. Shake hard for a thick foam. Fresh nutmeg is essential.',
    fun_fact:
      'The Alexander predates the Brandy Alexander; early-20th-century recipes used gin before brandy became the default base.',
    fun_fact_source: 'Early American cocktail manuals; IBA Unforgettables lineage',
    ingredients: '1 oz gin|1 oz dark crème de cacao|1 oz cream',
    instructions:
      '1. Shake gin, crème de cacao, and cream hard with ice. 2. Fine-strain into a chilled coupe. 3. Dust with freshly grated nutmeg.',
  },
  {
    slug: 'daiquiri-no-3',
    name: 'Daiquiri No. 3',
    short_description: 'A Floridita daiquiri of rum, lime, sugar, grapefruit, and maraschino.',
    long_description:
      'Daiquiri No. 3 is the Constantino Ribalaigua Vert / El Floridita template that later informed the Hemingway Daiquiri: white rum shaken with lime, sugar, grapefruit juice, and maraschino. Grapefruit and maraschino pull the daiquiri toward bittersweet citrus without abandoning the sour core. Served up (or blended in some historic service), it is a named classic in the daiquiri family.',
    seo_description: 'Shake a Daiquiri No. 3 with rum, lime, grapefruit, sugar, and maraschino.',
    base_spirit: 'Rum',
    category_primary: 'Sour',
    categories_all: 'classic|sour|daiquiri-family|rum|floridita',
    tags: 'rum|lime|grapefruit|maraschino|daiquiri|classic',
    image_alt: 'Daiquiri No. 3 in a coupe, pale pink-gold citrus, ungarnished or lime twist.',
    glassware: 'Coupe',
    garnish: 'lime twist optional',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 5,
    flavor_sweetness: 4,
    flavor_tartness: 7,
    flavor_bitterness: 2,
    flavor_aroma: 6,
    flavor_texture: 5,
    notes:
      'Keep maraschino measured—too much turns the drink sticky. Fresh grapefruit juice is mandatory. Distinct from a heavily reduced Hemingway with no sugar.',
    fun_fact:
      'At El Floridita in Havana, Constantino Ribalaigua Vert numbered daiquiri variations; No. 3 added grapefruit and maraschino and became the ancestor of the Hemingway Daiquiri.',
    fun_fact_source: 'El Floridita daiquiri histories; Cuban cocktail literature',
    ingredients: '2 oz white rum|0.75 oz fresh lime juice|0.5 oz fresh grapefruit juice|0.5 oz simple syrup|1 tsp maraschino liqueur',
    instructions:
      '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Garnish with a lime twist if desired.',
  },
  {
    slug: 'corpse-reviver-no-1',
    name: 'Corpse Reviver No. 1',
    short_description: 'A brandy morning cocktail of cognac, apple brandy, and sweet vermouth.',
    long_description:
      'Corpse Reviver No. 1 is the brandy sibling of the better-known No. 2: cognac and apple brandy stirred with sweet vermouth into a rich, spirit-forward restorative. Where No. 2 is citrus-bright gin, No. 1 is warming and wine-laced. Served up, it completes the classic Corpse Reviver pair.',
    seo_description: 'Stir a Corpse Reviver No. 1 with cognac, apple brandy, and sweet vermouth.',
    base_spirit: 'Cognac',
    category_primary: 'Spirit-Forward',
    categories_all: 'classic|spirit-forward|brunch|corpse-reviver|cognac',
    tags: 'cognac|apple-brandy|vermouth|brunch|classic|stirred',
    image_alt: 'Corpse Reviver No. 1 in a coupe, deep amber, optional orange twist.',
    glassware: 'Coupe',
    garnish: 'orange twist optional',
    technique: 'Stir',
    difficulty: 'Easy',
    flavor_strength: 8,
    flavor_sweetness: 4,
    flavor_tartness: 0,
    flavor_bitterness: 2,
    flavor_aroma: 7,
    flavor_texture: 5,
    notes: 'Equal parts is traditional. Calvados or applejack both work for the apple brandy leg.',
    fun_fact:
      'Savoy-era Corpse Revivers were marketed as hangover restoratives; No. 1 is the cognac version, No. 2 the gin-and-Cointreau sour.',
    fun_fact_source: 'The Savoy Cocktail Book; classic restorative cocktail histories',
    ingredients: '1 oz cognac|1 oz apple brandy|1 oz sweet vermouth',
    instructions:
      '1. Stir all ingredients with ice. 2. Strain into a chilled coupe. 3. Garnish with an orange twist if desired.',
  },
  {
    slug: 'coffee-cocktail',
    name: 'Coffee Cocktail',
    short_description: 'A classic flip of brandy, port, sugar, and egg—coffee-colored, no coffee.',
    long_description:
      'The Coffee Cocktail is an IBA Unforgettable that contains no coffee: brandy and ruby port shaken with sugar and a whole egg into a frothy, mahogany flip. Nutmeg finishes the drink. The name comes from its coffee-like color and after-dinner role, not from espresso.',
    seo_description: 'Shake a Coffee Cocktail with brandy, port, sugar, and egg for a classic flip.',
    base_spirit: 'Brandy',
    category_primary: 'Dessert',
    categories_all: 'classic|dessert|flip|brandy|port|iba',
    tags: 'brandy|port|egg|nutmeg|flip|classic',
    image_alt: 'Coffee Cocktail in a coupe or small wine glass, opaque mahogany foam, nutmeg dust.',
    glassware: 'Coupe',
    garnish: 'freshly grated nutmeg',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 6,
    flavor_sweetness: 5,
    flavor_tartness: 0,
    flavor_bitterness: 1,
    flavor_aroma: 6,
    flavor_texture: 9,
    notes: 'Dry-shake first for foam, then shake with ice. Ruby port keeps the color deep; tawny reads browner.',
    fun_fact:
      'Jerry Thomas listed a Coffee Cocktail that looks like coffee but uses brandy, port, and egg—no coffee bean required.',
    fun_fact_source: 'Jerry Thomas; IBA Unforgettables',
    ingredients: '1 oz brandy|1 oz ruby port|1 tsp sugar|1 whole egg',
    instructions:
      '1. Dry-shake all ingredients without ice. 2. Shake hard with ice. 3. Fine-strain into a chilled coupe. 4. Dust with nutmeg.',
  },
  {
    slug: 'brandy-flip',
    name: 'Brandy Flip',
    short_description: 'A spirit-forward flip of brandy, sugar, and whole egg, finished with nutmeg.',
    long_description:
      'The Brandy Flip is the clean template for the flip family: brandy, sugar, and a whole egg shaken to a thick foam and served up with nutmeg. Without port or cream, brandy character stays forward while egg gives body. It is the teaching drink for flip technique.',
    seo_description: 'Shake a Brandy Flip with brandy, sugar, and egg for a classic nutmeg-finished flip.',
    base_spirit: 'Brandy',
    category_primary: 'Dessert',
    categories_all: 'classic|dessert|flip|brandy',
    tags: 'brandy|egg|nutmeg|flip|classic',
    image_alt: 'Brandy Flip in a coupe, pale tan foam, nutmeg dust, ungarnished otherwise.',
    glassware: 'Coupe',
    garnish: 'freshly grated nutmeg',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 7,
    flavor_sweetness: 4,
    flavor_tartness: 0,
    flavor_bitterness: 0,
    flavor_aroma: 5,
    flavor_texture: 9,
    notes: 'Cognac elevates the drink. Dry-shake, then ice-shake. A splash of cream is optional but not traditional.',
    fun_fact:
      'Flips are among the oldest American mixed drinks; 19th-century bars served spirit, sugar, and egg long before cream cocktails dominated dessert menus.',
    fun_fact_source: '19th-century American bar manuals; flip histories',
    ingredients: '2 oz brandy or cognac|1 tsp sugar|1 whole egg',
    instructions:
      '1. Dry-shake brandy, sugar, and egg. 2. Shake hard with ice. 3. Fine-strain into a chilled coupe. 4. Dust with nutmeg.',
  },
  {
    slug: 'silver-fizz',
    name: 'Silver Fizz',
    short_description: 'A gin fizz with egg white—citrus, sugar, soda, and a soft foam cap.',
    long_description:
      'The Silver Fizz is a Gin Fizz with egg white: gin, lemon, sugar, and soda lengthened under a pale foam. The white adds texture without the richness of a yolk (Golden Fizz). Served tall, it sits between a sour and a sparkling highball.',
    seo_description: 'Shake a Silver Fizz with gin, lemon, sugar, egg white, and soda.',
    base_spirit: 'Gin',
    category_primary: 'Fizz',
    categories_all: 'classic|fizz|sour|gin|egg-white',
    tags: 'gin|lemon|egg-white|soda|fizz|classic',
    image_alt: 'Silver Fizz in a Collins glass, pale cloudy body, dense white foam cap, no fruit garnish.',
    glassware: 'Collins glass',
    garnish: 'None',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 4,
    flavor_sweetness: 4,
    flavor_tartness: 6,
    flavor_bitterness: 0,
    flavor_aroma: 5,
    flavor_texture: 8,
    notes: 'Dry-shake egg white first. Leave room for soda so the foam rises cleanly. No garnish keeps the foam visual clean.',
    fun_fact:
      'Silver, Golden, and Royal Fizzes differ by egg: white only, yolk only, or whole egg—same gin-citrus-soda architecture.',
    fun_fact_source: 'Classic fizz family bartending manuals',
    ingredients: '2 oz gin|1 oz fresh lemon juice|0.75 oz simple syrup|1 egg white|2 oz club soda',
    instructions:
      '1. Dry-shake gin, lemon, syrup, and egg white. 2. Shake hard with ice. 3. Strain into a Collins glass without ice (or over fresh ice). 4. Top with soda; serve ungarnished.',
  },
  {
    slug: 'chicago-fizz',
    name: 'Chicago Fizz',
    short_description: 'A rum-and-port fizz with lemon, egg white, sugar, and soda.',
    long_description:
      'The Chicago Fizz pairs aged rum and ruby port with lemon, sugar, egg white, and soda. Port deepens color and wine fruit while rum keeps the drink in sour-fizz territory. Served tall with a foam cap, it is a distinctive American classic outside the gin-fizz lane.',
    seo_description: 'Shake a Chicago Fizz with rum, port, lemon, egg white, sugar, and soda.',
    base_spirit: 'Rum',
    category_primary: 'Fizz',
    categories_all: 'classic|fizz|sour|rum|port',
    tags: 'rum|port|lemon|egg-white|soda|fizz',
    image_alt: 'Chicago Fizz in a Collins glass, pink-ruby body under white foam, ungarnished.',
    glassware: 'Collins glass',
    garnish: 'None',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 5,
    flavor_sweetness: 5,
    flavor_tartness: 5,
    flavor_bitterness: 1,
    flavor_aroma: 5,
    flavor_texture: 8,
    notes: 'Ruby port gives the signature color. Aged rum (not overproof) balances best.',
    fun_fact:
      'The Chicago Fizz appears in early-20th-century American bar books as a rum-and-port sparkling sour—an unusual twin-base fizz.',
    fun_fact_source: 'Early 20th-century American cocktail manuals',
    ingredients: '1 oz aged rum|1 oz ruby port|0.75 oz fresh lemon juice|0.5 oz simple syrup|1 egg white|2 oz club soda',
    instructions:
      '1. Dry-shake rum, port, lemon, syrup, and egg white. 2. Shake with ice. 3. Strain into a Collins glass. 4. Top with soda; serve ungarnished.',
  },
  {
    slug: 'pisco-punch',
    name: 'Pisco Punch',
    short_description: 'A historic San Francisco punch of pisco, pineapple, citrus, and sugar.',
    long_description:
      'Pisco Punch was the signature drink of San Francisco’s Bank Exchange saloon: pisco lengthened with pineapple, citrus, and sugar into a fragrant, dangerous-sipping punch. Modern single-serve versions keep pineapple and lemon (or lime) with a touch of gum syrup or simple syrup. It expands pisco beyond the sour.',
    seo_description: 'Build a Pisco Punch with pisco, pineapple, citrus, and sugar for the classic SF punch.',
    base_spirit: 'Pisco',
    category_primary: 'Punch',
    categories_all: 'classic|punch|pisco|pineapple|party',
    tags: 'pisco|pineapple|lemon|punch|classic|party',
    image_alt: 'Pisco Punch in a rocks or punch cup over ice, pale gold pineapple, pineapple leaf or mint.',
    glassware: 'Rocks glass',
    garnish: 'pineapple leaf|mint sprig',
    technique: 'Shake',
    difficulty: 'Intermediate',
    flavor_strength: 5,
    flavor_sweetness: 5,
    flavor_tartness: 5,
    flavor_bitterness: 0,
    flavor_aroma: 7,
    flavor_texture: 5,
    notes: 'Muddle a pineapple chunk or use fresh juice. Historic recipes were famously strong—measure the pisco.',
    fun_fact:
      'Pisco Punch made Duncan Nicol’s Bank Exchange in San Francisco legendary in the late 19th century; the exact original formula was closely guarded.',
    fun_fact_source: 'San Francisco bar history; pisco punch scholarship',
    ingredients: '2 oz pisco|1 oz fresh pineapple juice|0.75 oz fresh lemon juice|0.5 oz simple syrup|pineapple chunk optional',
    instructions:
      '1. Shake pisco, pineapple, lemon, and syrup with ice (muddle pineapple first if using fruit). 2. Strain over fresh ice in a rocks glass. 3. Garnish with pineapple leaf or mint.',
  },
  {
    slug: 'chilcano',
    name: 'Chilcano',
    short_description: 'A Peruvian highball of pisco, lime, ginger beer or ginger ale, and bitters.',
    long_description:
      'The Chilcano is Peru’s everyday pisco highball: pisco and lime topped with ginger beer or ginger ale, often with a dash of Angostura. It is brighter and spicier than a Pisco Sour and easier to build for a crowd. Served tall over ice, it is a summer and brunch natural.',
    seo_description: 'Build a Chilcano with pisco, lime, and ginger beer for a classic Peruvian highball.',
    base_spirit: 'Pisco',
    category_primary: 'Highball',
    categories_all: 'classic|highball|pisco|summer|brunch',
    tags: 'pisco|lime|ginger-beer|highball|peruvian|brunch|summer',
    image_alt: 'Chilcano in a highball over ice, pale gold ginger, lime wheel and optional bitters stain.',
    glassware: 'Highball glass',
    garnish: 'lime wheel',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 4,
    flavor_sweetness: 4,
    flavor_tartness: 5,
    flavor_bitterness: 1,
    flavor_aroma: 6,
    flavor_texture: 4,
    notes: 'Ginger beer is spicier; ginger ale is softer. A dash of Angostura is traditional in many Peruvian bars.',
    fun_fact:
      'Chilcanos are as common as Pisco Sours in Peru for casual drinking—pisco’s highball form rather than its shaken showpiece.',
    fun_fact_source: 'Peruvian bar practice; pisco category guides',
    ingredients: '2 oz pisco|0.5 oz fresh lime juice|4 oz ginger beer|1 dash Angostura bitters optional',
    instructions:
      '1. Fill a highball with ice. 2. Add pisco and lime. 3. Top with ginger beer and stir once. 4. Optional Angostura dash; garnish with lime.',
  },
  {
    slug: 'el-capitan',
    name: 'El Capitan',
    short_description: 'A stirred pisco cocktail with sweet vermouth—pisco’s Manhattan analogue.',
    long_description:
      'El Capitan stirs pisco with sweet vermouth (and often orange bitters) into a clear, wine-laced spirit-forward drink. It plays the Manhattan role for pisco: aromatic, compact, and served up or on a rock. It gives the catalog a stirred pisco classic beside the sour and highball.',
    seo_description: 'Stir an El Capitan with pisco and sweet vermouth for a classic pisco Manhattan-style cocktail.',
    base_spirit: 'Pisco',
    category_primary: 'Spirit-Forward',
    categories_all: 'classic|spirit-forward|pisco|vermouth|stirred',
    tags: 'pisco|sweet-vermouth|orange-bitters|stirred|classic',
    image_alt: 'El Capitan in a coupe, clear pale amber, orange twist.',
    glassware: 'Coupe',
    garnish: 'orange twist',
    technique: 'Stir',
    difficulty: 'Easy',
    flavor_strength: 7,
    flavor_sweetness: 3,
    flavor_tartness: 0,
    flavor_bitterness: 2,
    flavor_aroma: 7,
    flavor_texture: 5,
    notes: '2:1 pisco to vermouth keeps it dry; equal parts is richer. Acholado pisco works well.',
    fun_fact:
      'El Capitan is widely cited as the pisco-and-vermouth classic that mirrors Manhattan structure for South America’s grape brandy.',
    fun_fact_source: 'Modern pisco cocktail guides; classic stirred templates',
    ingredients: '2 oz pisco|1 oz sweet vermouth|2 dashes orange bitters',
    instructions:
      '1. Stir all ingredients with ice. 2. Strain into a chilled coupe. 3. Garnish with an expressed orange twist.',
  },
  {
    slug: 'rabo-de-galo',
    name: 'Rabo de Galo',
    short_description: 'A Brazilian stirred drink of cachaça, sweet vermouth, and Cynar or bitters.',
    long_description:
      'Rabo de Galo (“cocktail” in Brazilian bar slang) stirs cachaça with sweet vermouth and usually Cynar or Angostura into a compact aperitivo. It is Brazil’s answer to a spirit-and-vermouth short drink—bitter, grassy from cachaça, and sessionable before dinner.',
    seo_description: 'Stir a Rabo de Galo with cachaça, sweet vermouth, and Cynar for a Brazilian aperitivo.',
    base_spirit: 'Cachaça',
    category_primary: 'Spirit-Forward',
    categories_all: 'classic|spirit-forward|cachaca|aperitif|brazilian',
    tags: 'cachaca|vermouth|cynar|aperitivo|brazilian|stirred',
    image_alt: 'Rabo de Galo in a rocks glass over ice, deep amber-red, orange peel.',
    glassware: 'Rocks glass',
    garnish: 'orange peel',
    technique: 'Stir',
    difficulty: 'Easy',
    flavor_strength: 7,
    flavor_sweetness: 3,
    flavor_tartness: 0,
    flavor_bitterness: 6,
    flavor_aroma: 7,
    flavor_texture: 5,
    notes: 'Cynar is the modern bar default; Angostura-only versions are drier. Serve over a large cube.',
    fun_fact:
      'In Brazil, “rabo de galo” is everyday language for a mixed drink; the cachaça-vermouth-Cynar build became a national aperitivo staple.',
    fun_fact_source: 'Brazilian bar culture; modern cachaça cocktail writing',
    ingredients: '1.5 oz cachaça|0.75 oz sweet vermouth|0.5 oz Cynar',
    instructions:
      '1. Stir all ingredients with ice. 2. Strain over a large ice cube in a rocks glass. 3. Garnish with an orange peel.',
  },
  {
    slug: 'batida',
    name: 'Batida',
    short_description: 'A Brazilian blender or shaken drink of cachaça, fruit, and condensed milk or sugar.',
    long_description:
      'Batida is Brazil’s fruit-and-cachaça family: shaken or blended with passion fruit, coconut, or other fruit and often sweetened condensed milk. The passion-fruit (maracujá) version is bright and creamy. Served short over ice, it is a party-ready cachaça classic beyond the Caipirinha.',
    seo_description: 'Shake a Batida with cachaça, passion fruit, and sweetened condensed milk.',
    base_spirit: 'Cachaça',
    category_primary: 'Sour',
    categories_all: 'classic|sour|cachaca|fruit|brazilian|party',
    tags: 'cachaca|passion-fruit|condensed-milk|brazilian|party|summer',
    image_alt: 'Batida in a rocks glass over ice, opaque yellow passion-fruit cream, passion-fruit seed garnish.',
    glassware: 'Rocks glass',
    garnish: 'passion fruit half or mint',
    technique: 'Shake',
    difficulty: 'Easy',
    flavor_strength: 4,
    flavor_sweetness: 7,
    flavor_tartness: 5,
    flavor_bitterness: 0,
    flavor_aroma: 7,
    flavor_texture: 7,
    notes: 'Fresh passion fruit pulp beats syrup when possible. Condensed milk is traditional; simple syrup makes a lighter version.',
    fun_fact:
      'Batidas are a broad Brazilian category—cachaça plus fruit—popularized at home and in bars long before craft cocktail culture named individual riffs.',
    fun_fact_source: 'Brazilian drink culture; cachaça category guides',
    ingredients: '2 oz cachaça|1 oz passion fruit pulp or puree|0.75 oz sweetened condensed milk|0.5 oz fresh lime juice optional',
    instructions:
      '1. Shake cachaça, passion fruit, condensed milk, and optional lime with ice. 2. Strain over fresh ice in a rocks glass. 3. Garnish with passion fruit or mint.',
  },
  {
    slug: 'fish-house-punch',
    name: 'Fish House Punch',
    short_description: 'A historic Philadelphia punch of rum, cognac, peach, lemon, sugar, and tea or water.',
    long_description:
      'Fish House Punch is America’s most famous colonial-era punch: rum and cognac with peach brandy or peach liqueur, lemon, sugar, and cold black tea or water. It is built to batch, serve from a bowl, and drink slowly. A single-serve version keeps the same balance for modern hosting.',
    seo_description: 'Build Fish House Punch with rum, cognac, peach, lemon, and tea for the classic party punch.',
    base_spirit: 'Rum',
    category_primary: 'Punch',
    categories_all: 'classic|punch|rum|cognac|party|historic',
    tags: 'rum|cognac|peach|lemon|punch|party|classic',
    image_alt: 'Fish House Punch in a punch cup or rocks glass over ice, amber peach-citrus, lemon wheel and mint.',
    glassware: 'Punch cup',
    garnish: 'lemon wheel|mint sprig',
    technique: 'Build',
    difficulty: 'Intermediate',
    flavor_strength: 6,
    flavor_sweetness: 5,
    flavor_tartness: 5,
    flavor_bitterness: 1,
    flavor_aroma: 6,
    flavor_texture: 4,
    notes: 'Peach brandy is traditional; peach liqueur works. Brew tea strong and cool it before mixing. Scale freely for a bowl.',
    fun_fact:
      'Created at Philadelphia’s Schuylkill Fishing Company (the Fish House) in the 18th century, the punch was notorious for polite strength.',
    fun_fact_source: 'Schuylkill Fishing Company histories; American punch scholarship',
    ingredients: '1 oz aged rum|1 oz cognac|0.5 oz peach brandy or peach liqueur|0.75 oz fresh lemon juice|0.5 oz simple syrup|1 oz cold black tea',
    instructions:
      '1. Build all ingredients over ice in a punch cup or rocks glass (or combine in a bowl with a large ice block). 2. Stir. 3. Garnish with lemon and mint.',
  },
  {
    slug: 'whiskey-cobbler',
    name: 'Whiskey Cobbler',
    short_description: 'Whiskey shaken or built over crushed ice with sugar and citrus, fruit-garnished.',
    long_description:
      'The Whiskey Cobbler applies the cobbler template—spirit, sugar, citrus, crushed ice, and abundant fruit garnish—to whiskey. It is colder and fruitier than an Old Fashioned and more structured than a simple whiskey smash. Crushed ice and seasonal fruit define the look.',
    seo_description: 'Build a Whiskey Cobbler with whiskey, sugar, citrus, and crushed ice.',
    base_spirit: 'Whiskey',
    category_primary: 'Cobbler',
    categories_all: 'classic|cobbler|whiskey|crushed-ice|summer',
    tags: 'whiskey|crushed-ice|citrus|fruit|cobbler|classic',
    image_alt: 'Whiskey Cobbler in a cobbler or wine glass packed with jagged crushed ice, amber whiskey, orange and berries.',
    glassware: 'Wine glass',
    garnish: 'orange slice|berries|mint',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 6,
    flavor_sweetness: 4,
    flavor_tartness: 3,
    flavor_bitterness: 1,
    flavor_aroma: 5,
    flavor_texture: 5,
    notes: 'Bourbon is friendly; rye is drier. Pack real crushed ice—jagged shards, not pebble beads. Fruit garnish is part of the drink.',
    fun_fact:
      'Cobblers were among the most popular 19th-century American drinks; the Sherry Cobbler led, and whiskey versions followed the same crushed-ice formula.',
    fun_fact_source: '19th-century American cocktail histories; cobbler scholarship',
    ingredients: '3 oz whiskey|0.5 oz simple syrup|2 orange wheels|berries for garnish',
    instructions:
      '1. Muddle one orange wheel lightly with syrup in a wine glass. 2. Add whiskey and pack with crushed ice. 3. Stir until the glass frosts. 4. Top with more crushed ice and garnish with fruit and mint.',
  },
  {
    slug: 'port-sangaree',
    name: 'Port Sangaree',
    short_description: 'A historic low-ABV cooler of port, sugar, and grated nutmeg over ice.',
    long_description:
      'Port Sangaree is a 19th-century sangaree: port sweetened lightly, lengthened with ice (sometimes water), and finished with nutmeg. It is low-proof, wine-forward, and quietly aromatic—closer to an aperitif cooler than a cocktail in the modern sense. It fills a historic low-ABV gap beside cobblers and flips.',
    seo_description: 'Build a Port Sangaree with port, sugar, and nutmeg for a classic low-ABV cooler.',
    base_spirit: 'Wine',
    category_primary: 'Aperitif',
    categories_all: 'classic|aperitif|low-abv|port|historic',
    tags: 'port|nutmeg|low-abv|aperitif|classic',
    image_alt: 'Port Sangaree in a rocks or small wine glass over ice, deep ruby port, nutmeg dust.',
    glassware: 'Rocks glass',
    garnish: 'freshly grated nutmeg',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 4,
    flavor_sweetness: 6,
    flavor_tartness: 1,
    flavor_bitterness: 1,
    flavor_aroma: 6,
    flavor_texture: 4,
    notes: 'Ruby port is traditional. A splash of soda is optional for a longer drink. Keep sugar light.',
    fun_fact:
      'Sangarees—fortified wine, sugar, ice, and spice—were standard American bar coolers in the 1800s before ice-heavy cocktails took over.',
    fun_fact_source: '19th-century American bar manuals; sangaree histories',
    ingredients: '3 oz ruby port|0.25 oz simple syrup|freshly grated nutmeg',
    instructions:
      '1. Build port and syrup over ice in a rocks glass. 2. Stir briefly. 3. Dust generously with nutmeg.',
  },
  {
    slug: 'blackthorn',
    name: 'Blackthorn',
    short_description: 'An Irish whiskey cocktail with sweet vermouth, sloe gin or absinthe accents, and bitters.',
    long_description:
      'The Blackthorn is an Irish whiskey short drink that typically includes sweet vermouth with sloe gin, absinthe, or bitters depending on the era. Modern builds often stir Irish whiskey and vermouth with a rinse or dash of absinthe and bitters. It gives Irish whiskey a serious stirred classic beyond coffee and mule templates.',
    seo_description: 'Stir a Blackthorn with Irish whiskey, sweet vermouth, and absinthe or bitters.',
    base_spirit: 'Irish Whiskey',
    category_primary: 'Spirit-Forward',
    categories_all: 'classic|spirit-forward|irish-whiskey|vermouth|stirred',
    tags: 'irish-whiskey|vermouth|absinthe|bitters|stirred|classic',
    image_alt: 'Blackthorn in a coupe, deep amber, lemon twist.',
    glassware: 'Coupe',
    garnish: 'lemon twist',
    technique: 'Stir',
    difficulty: 'Intermediate',
    flavor_strength: 7,
    flavor_sweetness: 3,
    flavor_tartness: 0,
    flavor_bitterness: 3,
    flavor_aroma: 7,
    flavor_texture: 5,
    notes: 'Recipes vary widely. This stirred Irish whiskey–vermouth–absinthe version stays spirit-forward; sloe gin versions are fruitier.',
    fun_fact:
      'Blackthorn recipes appear in early-20th-century manuals with conflicting formulas—Irish whiskey is the consistent thread that distinguishes it from sloe-gin-only drinks of the same name.',
    fun_fact_source: 'Early 20th-century cocktail manuals; Irish whiskey cocktail histories',
    ingredients: '2 oz Irish whiskey|1 oz sweet vermouth|1 dash absinthe|2 dashes Angostura bitters',
    instructions:
      '1. Optional absinthe rinse of a chilled coupe. 2. Stir whiskey, vermouth, absinthe (if not rinsed), and bitters with ice. 3. Strain into the coupe. 4. Garnish with a lemon twist.',
  },
  {
    slug: 'cynar-spritz',
    name: 'Cynar Spritz',
    short_description: 'A bitter aperitivo spritz of Cynar, prosecco, and soda over ice.',
    long_description:
      'The Cynar Spritz applies the Venetian spritz template to artichoke amaro: Cynar, prosecco, and a splash of soda over ice with an orange slice. It is softer and more herbal than a Campari or Aperol spritz, with cola-like depth from Cynar. Ideal for aperitivo hour when bitterness should stay friendly.',
    seo_description: 'Build a Cynar Spritz with Cynar, prosecco, and soda for a bitter aperitivo spritz.',
    base_spirit: 'Aperitif',
    category_primary: 'Spritz',
    categories_all: 'aperitif|spritz|low-abv|cynar|italian',
    tags: 'cynar|prosecco|soda|aperitivo|spritz|low-abv',
    image_alt: 'Cynar Spritz in a wine glass over ice, deep cola-amber, orange slice.',
    glassware: 'Wine glass',
    garnish: 'orange slice',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 4,
    flavor_sweetness: 3,
    flavor_tartness: 1,
    flavor_bitterness: 6,
    flavor_aroma: 6,
    flavor_texture: 4,
    notes: 'Classic spritz proportions: 3 prosecco / 2 Cynar / 1 soda. Keep everything cold.',
    fun_fact:
      'Cynar Spritzes rose with the broader Italian spritz boom as drinkers wanted Campari-adjacent bitterness with a softer, vegetal amaro profile.',
    fun_fact_source: 'Italian aperitivo practice; modern spritz menus',
    ingredients: '2 oz Cynar|3 oz prosecco|1 oz club soda',
    instructions:
      '1. Fill a wine glass with ice. 2. Add Cynar. 3. Top with prosecco and soda. 4. Stir once; garnish with an orange slice.',
  },
  {
    slug: 'agua-de-valencia',
    name: 'Agua de Valencia',
    short_description: 'A Spanish brunch punch of orange juice, cava, gin, and vodka.',
    long_description:
      'Agua de Valencia (“Valencia water”) is a Valencian brunch punch: fresh orange juice fortified with gin and vodka, then lengthened with cava. It is brighter and stronger than a Mimosa, built for pitchers. Served cold in a flute or wine glass, it deepens the brunch occasion beyond orange-and-sparkling alone.',
    seo_description: 'Build Agua de Valencia with orange juice, cava, gin, and vodka for a Spanish brunch punch.',
    base_spirit: 'Wine',
    category_primary: 'Sparkling',
    categories_all: 'brunch|sparkling|punch|spanish|orange',
    tags: 'orange|cava|gin|vodka|brunch|spanish|party',
    image_alt: 'Agua de Valencia in a wine glass or flute, opaque orange, orange twist optional omit lemon.',
    glassware: 'Wine glass',
    garnish: 'orange twist optional',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 5,
    flavor_sweetness: 5,
    flavor_tartness: 4,
    flavor_bitterness: 0,
    flavor_aroma: 5,
    flavor_texture: 4,
    notes: 'Fresh orange juice only. Chill all components. Scale to a pitcher; add cava last so bubbles survive.',
    fun_fact:
      'Created in Valencia in the 1950s at Café Madrid de Valencia, Agua de Valencia became the city’s signature brunch and evening punch.',
    fun_fact_source: 'Valencian café history; Spanish brunch drink guides',
    ingredients: '2 oz fresh orange juice|0.5 oz gin|0.5 oz vodka|3 oz cava',
    instructions:
      '1. Add orange juice, gin, and vodka to a wine glass with ice (or a chilled flute without ice). 2. Top with cava. 3. Stir gently; optional orange twist.',
  },
  {
    slug: 'zero-proof-espresso-martini',
    name: 'Zero-Proof Espresso Martini',
    short_description: 'A non-alcoholic espresso cocktail with coffee, vanilla sweetness, and foam.',
    long_description:
      'The Zero-Proof Espresso Martini keeps espresso, sweetness, and a shaken foam without vodka or coffee liqueur. Non-alcoholic coffee aperitif or cold brew concentrate plus vanilla syrup stands in for the classic trio. Served up with coffee beans, it meets the biggest zero-proof demand gap beside the alcoholic Espresso Martini.',
    seo_description: 'Shake a Zero-Proof Espresso Martini with espresso and vanilla syrup for a non-alcoholic coffee cocktail.',
    base_spirit: 'Non-Alcoholic',
    category_primary: 'Coffee',
    categories_all: 'mocktail|coffee|zero-proof|dessert|brunch',
    tags: 'zero-proof|mocktail|espresso|coffee|brunch|dessert',
    image_alt: 'Zero-Proof Espresso Martini in a coupe, dark coffee with crema foam, three coffee beans.',
    glassware: 'Coupe',
    garnish: '3 coffee beans',
    technique: 'Shake',
    difficulty: 'Easy',
    flavor_strength: 4,
    flavor_sweetness: 5,
    flavor_tartness: 1,
    flavor_bitterness: 4,
    flavor_aroma: 8,
    flavor_texture: 7,
    notes: 'Fresh espresso or strong cold brew. NA coffee liqueur alternatives work if available. Shake very hard for foam.',
    fun_fact:
      'As Espresso Martinis surged in the 2020s, zero-proof versions became one of the most requested non-alcoholic “same but without” cocktail orders.',
    fun_fact_source: 'Modern zero-proof bar menus; espresso martini popularity trends',
    ingredients: '2 oz fresh espresso or strong cold brew|1 oz non-alcoholic coffee aperitif or cold brew concentrate|0.5 oz vanilla syrup|0.25 oz simple syrup optional',
    instructions:
      '1. Shake espresso, coffee aperitif/concentrate, and syrup hard with ice. 2. Fine-strain into a chilled coupe. 3. Garnish with three coffee beans.',
  },
  {
    slug: 'zero-proof-paloma',
    name: 'Zero-Proof Paloma',
    short_description: 'A non-alcoholic Paloma of grapefruit, lime, agave, and soda over ice.',
    long_description:
      'The Zero-Proof Paloma keeps grapefruit, lime, and agave from the classic Mexican highball and skips tequila—or uses a non-alcoholic agave spirit when available. Salted rim optional, soda for length. It pairs with the Zero-Proof Margarita as a core agave-style mocktail for summer hosting.',
    seo_description: 'Build a Zero-Proof Paloma with grapefruit, lime, agave, and soda for a non-alcoholic Paloma.',
    base_spirit: 'Non-Alcoholic',
    category_primary: 'Highball',
    categories_all: 'mocktail|highball|zero-proof|grapefruit|summer',
    tags: 'zero-proof|mocktail|grapefruit|lime|agave|summer|brunch',
    image_alt: 'Zero-Proof Paloma in a highball over ice, pale pink grapefruit, grapefruit wedge, optional salt rim.',
    glassware: 'Highball glass',
    garnish: 'grapefruit wedge|optional salt rim',
    technique: 'Build',
    difficulty: 'Easy',
    flavor_strength: 2,
    flavor_sweetness: 4,
    flavor_tartness: 6,
    flavor_bitterness: 2,
    flavor_aroma: 5,
    flavor_texture: 4,
    notes: 'Fresh grapefruit juice beats soda alone. NA tequila optional; without it, keep agave and citrus assertive.',
    fun_fact:
      'Palomas already drink like a grapefruit soda highball—removing tequila still leaves a complete, bitter-citrus cooler that hosts well.',
    fun_fact_source: 'Modern zero-proof and Mexican-inspired mocktail menus',
    ingredients: '3 oz fresh grapefruit juice|0.5 oz fresh lime juice|0.5 oz agave syrup|2 oz club soda|optional 1.5 oz non-alcoholic tequila alternative|optional salt rim',
    instructions:
      '1. Optional salt half-rim. 2. Build grapefruit, lime, agave, and optional NA tequila over ice. 3. Top with soda and stir once. 4. Garnish with grapefruit.',
  },
];

function csvEscape(v: string | number) {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main() {
  const headers = [
    'ID',
    'slug',
    'name',
    'short_description',
    'long_description',
    'seo_description',
    'base_spirit',
    'category_primary',
    'categories_all',
    'tags',
    'image_url',
    'image_alt',
    'glassware',
    'garnish',
    'technique',
    'difficulty',
    'flavor_strength',
    'flavor_sweetness',
    'flavor_tartness',
    'flavor_bitterness',
    'flavor_aroma',
    'flavor_texture',
    'notes',
    'fun_fact',
    'fun_fact_source',
    'metadata_json',
    'ingredients',
    'instructions',
  ];
  const rows = drafts.map((d, i) =>
    [
      `mw_review_007_${String(i + 1).padStart(3, '0')}`,
      d.slug,
      d.name,
      d.short_description,
      d.long_description,
      d.seo_description,
      d.base_spirit,
      d.category_primary,
      d.categories_all,
      d.tags,
      '',
      d.image_alt,
      d.glassware,
      d.garnish,
      d.technique,
      d.difficulty,
      d.flavor_strength,
      d.flavor_sweetness,
      d.flavor_tartness,
      d.flavor_bitterness,
      d.flavor_aroma,
      d.flavor_texture,
      d.notes,
      d.fun_fact,
      d.fun_fact_source,
      '{}',
      d.ingredients,
      d.instructions,
    ]
      .map(csvEscape)
      .join(',')
  );
  const out = path.join(process.cwd(), 'data', 'review-batch-007.csv');
  fs.writeFileSync(out, [headers.join(','), ...rows].join('\n') + '\n');
  console.log(`Wrote ${drafts.length} → ${out}`);
  console.log(drafts.map((d) => d.slug).join('\n'));
}

main();
