#!/usr/bin/env tsx
/** Generate review-batch-003.csv — fall / autumn drinks. */
import * as fs from 'fs';
import * as path from 'path';

type Draft = {
  slug: string; name: string; short_description: string; long_description: string; seo_description: string;
  base_spirit: string; category_primary: string; categories_all: string; tags: string; image_alt: string;
  glassware: string; garnish: string; technique: 'Shake' | 'Stir' | 'Build' | 'Blend' | 'Swizzle';
  difficulty: 'Easy' | 'Intermediate' | 'Advanced';
  flavor_strength: number; flavor_sweetness: number; flavor_tartness: number; flavor_bitterness: number;
  flavor_aroma: number; flavor_texture: number;
  notes: string; fun_fact: string; fun_fact_source: string; ingredients: string; instructions: string;
};

const drafts: Draft[] = [
  {
    slug: 'apple-cider-old-fashioned',
    name: 'Apple Cider Old Fashioned',
    short_description: 'An Old Fashioned sweetened with apple cider and maple for a clear autumn profile.',
    long_description: 'The Apple Cider Old Fashioned keeps whiskey, bitters, and a large ice cube, then folds in reduced apple cider or cider syrup and maple. Apple and spice sit under the whiskey without turning the drink into punch. Served on a rock with an orange peel, it is a straightforward fall variation on a classic template.',
    seo_description: 'Stir an Apple Cider Old Fashioned with whiskey, apple cider, maple, and bitters for a classic fall cocktail.',
    base_spirit: 'Bourbon', category_primary: 'Spirit-Forward', categories_all: 'fall|spirit-forward|old-fashioned-family|seasonal',
    tags: 'bourbon|apple-cider|maple|bitters|fall',
    image_alt: 'Apple Cider Old Fashioned in a rocks glass over a large ice cube, amber, orange peel garnish.',
    glassware: 'Rocks glass', garnish: 'orange peel', technique: 'Stir', difficulty: 'Easy',
    flavor_strength: 8, flavor_sweetness: 4, flavor_tartness: 2, flavor_bitterness: 4, flavor_aroma: 7, flavor_texture: 6,
    notes: 'Reduce cider briefly for intensity, or use a concentrated cider syrup. Keep sweetness below a dessert profile.',
    fun_fact: 'Apple cider Old Fashioned variations proliferated with craft-bar seasonal menus as a way to keep the whiskey template while signaling autumn.',
    fun_fact_source: 'Modern craft cocktail seasonal menu practice',
    ingredients: '2 oz bourbon|0.5 oz apple cider syrup|0.25 oz maple syrup|2 dashes Angostura bitters|1 dash orange bitters',
    instructions: '1. Stir bourbon, cider syrup, maple, and bitters with ice. 2. Strain over a large ice cube in a rocks glass. 3. Garnish with an expressed orange peel.',
  },
  {
    slug: 'spiked-apple-cider',
    name: 'Spiked Apple Cider',
    short_description: 'Warm apple cider fortified with whiskey or rum and finished with spice.',
    long_description: 'Spiked Apple Cider is a hot fall drink built from mulled or warmed cider and a measure of whiskey or dark rum. Cinnamon and clove perfume the cider while the spirit adds warmth without masking the apple. Served in a mug, it is communal, seasonal, and easy to batch for gatherings.',
    seo_description: 'Build Spiked Apple Cider with warm cider, whiskey, and spice for a classic fall hot cocktail.',
    base_spirit: 'Whiskey', category_primary: 'Hot', categories_all: 'fall|hot|seasonal|party',
    tags: 'apple-cider|whiskey|cinnamon|hot|fall',
    image_alt: 'Spiked Apple Cider in a mug, amber, cinnamon stick garnish, faint steam.',
    glassware: 'Mug', garnish: 'cinnamon stick|orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 5, flavor_tartness: 2, flavor_bitterness: 1, flavor_aroma: 8, flavor_texture: 5,
    notes: 'Warm cider below a boil. Add spirit in the mug so alcohol does not cook off aggressively.',
    fun_fact: 'Fortified cider drinks are longstanding cold-weather tavern fare in apple-growing regions of North America and Europe.',
    fun_fact_source: 'American and European cider drinking traditions',
    ingredients: '6 oz warm apple cider|2 oz whiskey|0.25 oz maple syrup optional|1 cinnamon stick|2 cloves|orange peel',
    instructions: '1. Warm cider with cinnamon and cloves. 2. Add whiskey and optional maple to a warmed mug. 3. Top with the hot cider. 4. Garnish with cinnamon stick and orange peel.',
  },
  {
    slug: 'maple-old-fashioned',
    name: 'Maple Old Fashioned',
    short_description: 'A whiskey Old Fashioned sweetened with maple syrup instead of sugar.',
    long_description: 'The Maple Old Fashioned replaces simple syrup or sugar with maple, keeping bitters and a large cube intact. Maple adds caramel and wood notes that reinforce bourbon or rye without turning the drink sticky when measured carefully. It is one of the cleanest seasonal Old Fashioned variants.',
    seo_description: 'Stir a Maple Old Fashioned with whiskey, maple syrup, and bitters for a classic fall whiskey cocktail.',
    base_spirit: 'Bourbon', category_primary: 'Spirit-Forward', categories_all: 'fall|spirit-forward|old-fashioned-family',
    tags: 'bourbon|maple|bitters|stirred|fall',
    image_alt: 'Maple Old Fashioned in a rocks glass over a large ice cube, deep amber, orange peel.',
    glassware: 'Rocks glass', garnish: 'orange peel', technique: 'Stir', difficulty: 'Easy',
    flavor_strength: 8, flavor_sweetness: 4, flavor_tartness: 1, flavor_bitterness: 4, flavor_aroma: 7, flavor_texture: 6,
    notes: 'Use real maple syrup, preferably grade A dark for flavor. Start at a quarter-ounce and adjust.',
    fun_fact: 'Maple as an Old Fashioned sweetener became common in North American craft bars where maple is a regional pantry staple.',
    fun_fact_source: 'Modern North American craft cocktail practice',
    ingredients: '2 oz bourbon|0.25 oz maple syrup|2 dashes Angostura bitters|1 dash orange bitters',
    instructions: '1. Stir bourbon, maple, and bitters with ice. 2. Strain over a large ice cube. 3. Garnish with an expressed orange peel.',
  },
  {
    slug: 'applejack-rabbit',
    name: 'Applejack Rabbit',
    short_description: 'A Prohibition-era apple brandy sour with maple and citrus.',
    long_description: 'The Applejack Rabbit combines apple brandy with lemon, orange, and maple into a bright autumn sour. Apple character leads, maple softens, and citrus keeps the drink from reading as dessert. Shaken and served up, it is a historical fall cocktail with a clear structural identity.',
    seo_description: 'Shake an Applejack Rabbit with apple brandy, maple, lemon, and orange for a classic autumn sour.',
    base_spirit: 'Apple Brandy', category_primary: 'Sour', categories_all: 'fall|sour|classic|apple',
    tags: 'apple-brandy|maple|lemon|orange|fall',
    image_alt: 'Applejack Rabbit in a chilled coupe, golden amber, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Fresh citrus is essential. Calvados or bonded apple brandy both work; adjust maple to the spirit’s sweetness.',
    fun_fact: 'The Applejack Rabbit appears in Prohibition-era sources as an apple brandy cocktail using maple and citrus.',
    fun_fact_source: 'Prohibition-era American cocktail manuals; Imbibe histories',
    ingredients: '2 oz apple brandy|0.75 oz fresh lemon juice|0.5 oz fresh orange juice|0.5 oz maple syrup',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'cranberry-mule',
    name: 'Cranberry Mule',
    short_description: 'A mule highball with vodka, cranberry, lime, and ginger beer.',
    long_description: 'The Cranberry Mule keeps the mule’s ginger-lime frame and adds cranberry for tart fall color and flavor. Vodka stays neutral under spice and berry acidity. Served over ice in a highball or copper mug, it is an easy seasonal party drink.',
    seo_description: 'Build a Cranberry Mule with vodka, cranberry juice, lime, and ginger beer for a fall highball.',
    base_spirit: 'Vodka', category_primary: 'Highball', categories_all: 'fall|highball|mule-family|party',
    tags: 'vodka|cranberry|ginger-beer|lime|fall',
    image_alt: 'Cranberry Mule in a copper mug or highball over ice, deep red, lime wheel.',
    glassware: 'Highball glass', garnish: 'lime wheel|fresh cranberries', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 4, flavor_tartness: 6, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 4,
    notes: 'Use a spicy ginger beer. Unsweetened or lightly sweetened cranberry keeps the drink from becoming candy-like.',
    fun_fact: 'Cranberry mule variations became common seasonal specials as bars adapted the Moscow Mule template to fall flavors.',
    fun_fact_source: 'Modern mule variation menus',
    ingredients: '2 oz vodka|1 oz cranberry juice|0.5 oz fresh lime juice|4 oz ginger beer',
    instructions: '1. Build vodka, cranberry, and lime over ice. 2. Top with ginger beer and stir gently. 3. Garnish with lime and cranberries.',
  },
  {
    slug: 'autumn-spritz',
    name: 'Autumn Spritz',
    short_description: 'A sparkling fall spritz with amaro, apple cider, and Prosecco.',
    long_description: 'The Autumn Spritz applies the spritz template to fall pantry flavors: a bitter amaro for depth, apple cider for seasonal sweetness, and Prosecco for lift. Served over ice in a wine glass, it is lighter than a hot cider drink but clearly autumn-coded.',
    seo_description: 'Build an Autumn Spritz with amaro, apple cider, and Prosecco for a sparkling fall cocktail.',
    base_spirit: 'Liqueur', category_primary: 'Spritz', categories_all: 'fall|spritz|sparkling|seasonal',
    tags: 'amaro|apple-cider|prosecco|spritz|fall',
    image_alt: 'Autumn Spritz in a wine glass over ice, amber-gold, apple slice garnish.',
    glassware: 'Wine glass', garnish: 'apple slice', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 4, flavor_tartness: 2, flavor_bitterness: 4, flavor_aroma: 7, flavor_texture: 4,
    notes: 'Averna, Nonino, or similar medium amaro works. Keep cider dryish so the spritz stays refreshing.',
    fun_fact: 'Seasonal spritzes expanded with the spritz boom as bars swapped bitter aperitivi and fruit for calendar-specific flavors.',
    fun_fact_source: 'Modern aperitivo and spritz menu practice',
    ingredients: '1.5 oz amaro|1.5 oz apple cider|3 oz Prosecco|1 oz club soda',
    instructions: '1. Fill a wine glass with ice. 2. Add amaro and cider. 3. Top with Prosecco and soda. 4. Garnish with an apple slice.',
  },
  {
    slug: 'mulled-wine',
    name: 'Mulled Wine',
    short_description: 'Warm spiced red wine with citrus and winter spices for cold-weather serving.',
    long_description: 'Mulled Wine gently heats red wine with citrus, cinnamon, clove, and sweetener. The goal is aromatic warmth without boiling off the wine’s character. Served in a mug, it is a foundational fall and winter communal drink across Europe and North America.',
    seo_description: 'Warm Mulled Wine with red wine, citrus, and spice for a classic fall and winter drink.',
    base_spirit: 'Wine', category_primary: 'Hot', categories_all: 'fall|winter|hot|seasonal|party',
    tags: 'wine|cinnamon|clove|orange|hot|fall',
    image_alt: 'Mulled Wine in a mug, deep red, cinnamon stick and orange peel, light steam.',
    glassware: 'Mug', garnish: 'cinnamon stick|orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 5, flavor_tartness: 2, flavor_bitterness: 2, flavor_aroma: 9, flavor_texture: 5,
    notes: 'Keep below a simmer. Add a splash of brandy only at the end if fortifying.',
    fun_fact: 'Mulled wine traditions span European winter markets and holidays, with regional spice blends under names like Glühwein.',
    fun_fact_source: 'European winter market and wine traditions',
    ingredients: '1 bottle dry red wine|2 oz brandy optional|3 oz fresh orange juice|2 oz honey or sugar|2 cinnamon sticks|4 cloves|2 star anise|orange peel',
    instructions: '1. Warm wine with citrus, sweetener, and spices over low heat. 2. Do not boil. 3. Strain into mugs. 4. Garnish with cinnamon and orange peel.',
  },
  {
    slug: 'tom-and-jerry',
    name: 'Tom and Jerry',
    short_description: 'A hot eggnog-style drink built from a spiced batter, spirit, and hot milk.',
    long_description: 'The Tom and Jerry is a hot batter drink related to eggnog: a sweet spiced egg batter is loosened with brandy and rum, then finished with hot milk or water. Rich, aromatic, and festive, it is strongly associated with Midwest American winter service. The batter is the technique that defines the drink.',
    seo_description: 'Build a Tom and Jerry with spiced egg batter, brandy, rum, and hot milk for a classic winter cocktail.',
    base_spirit: 'Brandy', category_primary: 'Hot', categories_all: 'fall|winter|hot|holiday|classic',
    tags: 'brandy|rum|egg|hot|batter|holiday',
    image_alt: 'Tom and Jerry in a mug, creamy pale, nutmeg dusting, light steam.',
    glassware: 'Mug', garnish: 'grated nutmeg', technique: 'Build', difficulty: 'Advanced',
    flavor_strength: 5, flavor_sweetness: 6, flavor_tartness: 0, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 9,
    notes: 'Make batter ahead. Use pasteurized eggs if preferred. Hot milk gives a richer finish than water.',
    fun_fact: 'The Tom and Jerry is often linked to nineteenth-century American bartender Jerry Thomas and remains a Midwest holiday specialty.',
    fun_fact_source: 'Jerry Thomas cocktail histories; Midwest holiday bar traditions',
    ingredients: '1 oz brandy|1 oz dark rum|2 tbsp Tom and Jerry batter|4 oz hot milk|grated nutmeg',
    instructions: '1. Add batter to a warmed mug. 2. Stir in brandy and rum until smooth. 3. Top with hot milk and stir. 4. Dust with nutmeg.',
  },
  {
    slug: 'brandy-milk-punch',
    name: 'Brandy Milk Punch',
    short_description: 'A New Orleans brandy cocktail with milk, sugar, and nutmeg over ice.',
    long_description: 'Brandy Milk Punch is a creamy stirred or shaken milk cocktail associated with New Orleans brunch and cooler weather. Brandy, milk, sugar, and vanilla create a soft dessert-leaning profile finished with nutmeg. Served over ice, it is richer than a sour and lighter than hot eggnog.',
    seo_description: 'Shake a Brandy Milk Punch with brandy, milk, sugar, and nutmeg for a classic New Orleans cocktail.',
    base_spirit: 'Brandy', category_primary: 'Dessert', categories_all: 'fall|dessert|classic|new-orleans',
    tags: 'brandy|milk|nutmeg|cream|brunch',
    image_alt: 'Brandy Milk Punch in a rocks glass over ice, creamy white, nutmeg dusting.',
    glassware: 'Rocks glass', garnish: 'grated nutmeg', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 5, flavor_sweetness: 5, flavor_tartness: 0, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 8,
    notes: 'Whole milk or a mix of milk and cream works. Shake hard for chill and froth.',
    fun_fact: 'Milk punch has deep roots in early American and English drinking, with the brandy version closely tied to New Orleans service.',
    fun_fact_source: 'New Orleans cocktail histories; early milk punch traditions',
    ingredients: '2 oz brandy|4 oz whole milk|0.75 oz simple syrup|0.25 oz vanilla extract|grated nutmeg',
    instructions: '1. Shake brandy, milk, syrup, and vanilla with ice. 2. Strain into a rocks glass over ice. 3. Dust with nutmeg.',
  },
  {
    slug: 'horses-neck',
    name: "Horse's Neck",
    short_description: 'A long highball of brandy or whiskey with ginger ale and a long lemon peel.',
    long_description: 'The Horse’s Neck is a simple highball defined by its long spiral citrus peel hanging over the rim. Brandy or whiskey sits under ginger ale for a light, spicy length. It reads as an approachable cooler-weather highball with classic presentation.',
    seo_description: "Build a Horse's Neck with brandy, ginger ale, and a long citrus peel for a classic highball.",
    base_spirit: 'Brandy', category_primary: 'Highball', categories_all: 'fall|highball|classic|easy',
    tags: 'brandy|ginger-ale|citrus-peel|highball',
    image_alt: "Horse's Neck in a highball over ice with a long citrus peel hanging over the rim.",
    glassware: 'Highball glass', garnish: 'long orange peel', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 4, flavor_tartness: 1, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 4,
    notes: 'The long peel is mandatory to the identity of the drink. A dash of bitters is optional but traditional in some versions.',
    fun_fact: 'The Horse’s Neck takes its name from the long hanging peel, said to resemble a horse’s neck draped over the glass.',
    fun_fact_source: 'Classic highball cocktail histories',
    ingredients: '2 oz brandy|4 oz ginger ale|2 dashes Angostura bitters optional|long orange peel',
    instructions: '1. Place a long orange peel in a highball glass so it hangs over the rim. 2. Add ice and brandy. 3. Top with ginger ale and optional bitters. 4. Stir once.',
  },
  {
    slug: 'brandy-crusta',
    name: 'Brandy Crusta',
    short_description: 'A nineteenth-century Cognac sour with a sugared rim and wide citrus peel.',
    long_description: 'The Brandy Crusta is an early sour relative of the Sidecar: Cognac, citrus, and orange liqueur in a glass with a sugared rim and an expansive peel. It is aromatic, slightly sweet, and historically important to the sour family. Served up, it has a clear fall-winter brandy character.',
    seo_description: 'Shake a Brandy Crusta with Cognac, lemon, and orange liqueur for a classic sugared-rim sour.',
    base_spirit: 'Cognac', category_primary: 'Sour', categories_all: 'fall|sour|classic|brandy',
    tags: 'cognac|orange-liqueur|lemon|sugar-rim|classic',
    image_alt: 'Brandy Crusta in a small wine or coupe glass with sugared rim and wide citrus peel, golden.',
    glassware: 'Coupe', garnish: 'wide orange peel|sugared rim', technique: 'Shake', difficulty: 'Intermediate',
    flavor_strength: 7, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Sugar only the outer rim. The wide peel should stand inside the glass as a lining in traditional presentations.',
    fun_fact: 'Joseph Santini is credited with the Crusta in mid-nineteenth-century New Orleans, an important ancestor of later brandy sours.',
    fun_fact_source: 'David Wondrich, Imbibe!; New Orleans cocktail histories',
    ingredients: '2 oz Cognac|0.5 oz orange liqueur|0.75 oz fresh lemon juice|0.25 oz simple syrup|2 dashes Angostura bitters|sugar for rim',
    instructions: '1. Sugar the outer rim of a chilled coupe. 2. Shake Cognac, liqueur, lemon, syrup, and bitters with ice. 3. Strain into the glass. 4. Fit a wide orange peel inside as garnish.',
  },
  {
    slug: 'stone-fence',
    name: 'Stone Fence',
    short_description: 'A rustic highball of whiskey or apple brandy topped with hard cider.',
    long_description: 'The Stone Fence is a simple cider-and-spirit highball with deep American roots. Whiskey or apple brandy is lengthened with hard cider over ice for a dry, orchard-forward drink. It is intentionally rustic and well suited to fall.',
    seo_description: 'Build a Stone Fence with whiskey and hard cider for a classic American fall highball.',
    base_spirit: 'Whiskey', category_primary: 'Highball', categories_all: 'fall|highball|classic|cider',
    tags: 'whiskey|hard-cider|fall|rustic',
    image_alt: 'Stone Fence in a highball over ice, pale gold, apple slice optional.',
    glassware: 'Highball glass', garnish: 'apple slice', technique: 'Build', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 2, flavor_tartness: 3, flavor_bitterness: 1, flavor_aroma: 5, flavor_texture: 4,
    notes: 'Use a dry hard cider. Apple brandy makes a more orchard-forward variant.',
    fun_fact: 'The Stone Fence appears in early American drinking lore as a cider-fortified tavern drink, later standardized with whiskey or apple spirit.',
    fun_fact_source: 'Early American drinking histories; cider tavern traditions',
    ingredients: '2 oz whiskey|5 oz hard cider|2 dashes Angostura bitters optional',
    instructions: '1. Add whiskey to a highball glass with ice. 2. Top with hard cider. 3. Add optional bitters and stir once. 4. Garnish with an apple slice.',
  },
  {
    slug: 'caramel-apple-martini',
    name: 'Caramel Apple Martini',
    short_description: 'A dessert-leaning vodka martini with apple and caramel flavors.',
    long_description: 'The Caramel Apple Martini is a modern party cocktail that plays to fall dessert flavors: vodka, apple liqueur or juice, and caramel syrup or butterscotch liqueur. Shaken and served up, it is sweet, recognizable, and seasonal rather than spirit-forward.',
    seo_description: 'Shake a Caramel Apple Martini with vodka, apple, and caramel for a fall party cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'fall|dessert|party|seasonal',
    tags: 'vodka|apple|caramel|martini|fall',
    image_alt: 'Caramel Apple Martini in a coupe, golden amber, ungarnished or caramel rim.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 8, flavor_tartness: 2, flavor_bitterness: 0, flavor_aroma: 6, flavor_texture: 5,
    notes: 'Keep caramel restrained or the drink turns syrupy. Fresh apple cider can replace some liqueur for brightness.',
    fun_fact: 'Caramel apple martinis emerged with early-2000s flavored martini menus that translated seasonal desserts into shaken vodka drinks.',
    fun_fact_source: 'Early-2000s American flavored martini menus',
    ingredients: '1.5 oz vodka|1 oz apple liqueur|0.75 oz butterscotch or caramel liqueur|0.5 oz fresh lemon juice optional',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'pumpkin-spice-martini',
    name: 'Pumpkin Spice Martini',
    short_description: 'A seasonal vodka dessert martini with pumpkin spice and cream liqueur.',
    long_description: 'The Pumpkin Spice Martini is an explicitly seasonal dessert cocktail using vodka, pumpkin puree or pumpkin liqueur, spice, and a creamy element. Shaken and served up, it prioritizes recognizable fall flavor over classic structure. Restraint with puree keeps texture drinkable.',
    seo_description: 'Shake a Pumpkin Spice Martini with vodka, pumpkin, and spice for a seasonal fall dessert cocktail.',
    base_spirit: 'Vodka', category_primary: 'Dessert', categories_all: 'fall|dessert|party|seasonal',
    tags: 'vodka|pumpkin|spice|cream|fall',
    image_alt: 'Pumpkin Spice Martini in a coupe, pale orange-tan, light spice dusting.',
    glassware: 'Coupe', garnish: 'grated nutmeg', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 4, flavor_sweetness: 7, flavor_tartness: 1, flavor_bitterness: 0, flavor_aroma: 8, flavor_texture: 7,
    notes: 'Use a small amount of pumpkin puree and strain well, or prefer pumpkin spice liqueur for cleaner texture.',
    fun_fact: 'Pumpkin spice cocktails tracked the broader pumpkin-spice food trend into early-twenty-first-century bar menus.',
    fun_fact_source: 'Modern seasonal cocktail menu trends',
    ingredients: '1.5 oz vodka|1 oz Irish cream or coffee liqueur|0.75 oz pumpkin spice syrup|0.5 oz heavy cream|pinch pumpkin spice',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Dust lightly with nutmeg or pumpkin spice.',
  },
  {
    slug: 'spiced-pear-cocktail',
    name: 'Spiced Pear Cocktail',
    short_description: 'A fall sour with pear brandy or liqueur, lemon, and warm spice.',
    long_description: 'The Spiced Pear Cocktail builds a sour around pear character and autumn spice. Pear brandy or liqueur provides the fruit core, lemon keeps it bright, and a spice syrup ties it to the season. Shaken and served up, it is cleaner than dessert martinis while still clearly fall.',
    seo_description: 'Shake a Spiced Pear Cocktail with pear brandy, lemon, and spice syrup for a fall sour.',
    base_spirit: 'Brandy', category_primary: 'Sour', categories_all: 'fall|sour|seasonal|pear',
    tags: 'pear|brandy|spice|lemon|fall',
    image_alt: 'Spiced Pear Cocktail in a coupe, pale gold, ungarnished.',
    glassware: 'Coupe', garnish: 'None', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 7, flavor_texture: 5,
    notes: 'Poire Williams or a quality pear liqueur both work; reduce syrup if using a sweet liqueur.',
    fun_fact: 'Pear-and-spice sours became common craft-bar autumn specials as pear eau-de-vie and liqueurs gained wider distribution.',
    fun_fact_source: 'Modern craft seasonal cocktail menus',
    ingredients: '1.5 oz pear brandy|0.5 oz vodka optional|0.75 oz fresh lemon juice|0.75 oz spiced syrup',
    instructions: '1. Shake all ingredients with ice. 2. Fine-strain into a chilled coupe. 3. Serve ungarnished.',
  },
  {
    slug: 'apple-cider-margarita',
    name: 'Apple Cider Margarita',
    short_description: 'A tequila margarita variation using apple cider with lime and orange liqueur.',
    long_description: 'The Apple Cider Margarita keeps the margarita’s tequila-lime-orange-liqueur frame and swaps part of the sweetener/citrus balance for apple cider. Agave and apple share the mid-palate while lime preserves snap. Served on the rocks, it is a fall patio and dinner-party tequila option.',
    seo_description: 'Shake an Apple Cider Margarita with tequila, apple cider, lime, and orange liqueur for a fall twist.',
    base_spirit: 'Tequila', category_primary: 'Sour', categories_all: 'fall|sour|margarita-family|seasonal',
    tags: 'tequila|apple-cider|lime|margarita|fall',
    image_alt: 'Apple Cider Margarita in a rocks glass over ice, pale gold, cinnamon-sugar rim optional.',
    glassware: 'Rocks glass', garnish: 'apple slice|optional cinnamon sugar rim', technique: 'Shake', difficulty: 'Easy',
    flavor_strength: 6, flavor_sweetness: 4, flavor_tartness: 5, flavor_bitterness: 1, flavor_aroma: 6, flavor_texture: 5,
    notes: 'Use 100% agave blanco or reposado. A light cinnamon-sugar half rim is optional and seasonal.',
    fun_fact: 'Apple cider margaritas spread as a seasonal margarita riff once fall cider became a standard bar modifier.',
    fun_fact_source: 'Modern seasonal margarita menus',
    ingredients: '2 oz blanco tequila|1 oz apple cider|0.75 oz fresh lime juice|0.5 oz Cointreau',
    instructions: '1. Optional: rim half the glass with cinnamon sugar. 2. Shake tequila, cider, lime, and Cointreau with ice. 3. Strain over fresh ice. 4. Garnish with an apple slice.',
  },
  {
    slug: 'smoked-old-fashioned',
    name: 'Smoked Old Fashioned',
    short_description: 'An Old Fashioned finished with smoke for aroma and cooler-weather drama.',
    long_description: 'The Smoked Old Fashioned keeps the classic whiskey-sugar-bitters structure and adds wood smoke to the glass or spirit. Smoke heightens aroma and pairs naturally with fall and winter service. The underlying drink should remain balanced; smoke is seasoning, not the recipe.',
    seo_description: 'Stir a Smoked Old Fashioned with whiskey, sugar, and bitters, finished with wood smoke.',
    base_spirit: 'Bourbon', category_primary: 'Spirit-Forward', categories_all: 'fall|spirit-forward|old-fashioned-family|seasonal',
    tags: 'bourbon|smoke|bitters|old-fashioned|fall',
    image_alt: 'Smoked Old Fashioned in a rocks glass over a large ice cube, amber, orange peel, faint smoke.',
    glassware: 'Rocks glass', garnish: 'orange peel', technique: 'Stir', difficulty: 'Intermediate',
    flavor_strength: 9, flavor_sweetness: 3, flavor_tartness: 1, flavor_bitterness: 4, flavor_aroma: 9, flavor_texture: 6,
    notes: 'Capture smoke under a cloche or rinse the glass briefly. Over-smoking turns the drink acrid.',
    fun_fact: 'Tableside smoking became a craft-bar flourish in the 2000s and 2010s, especially on Old Fashioned variations.',
    fun_fact_source: 'Modern craft cocktail presentation trends',
    ingredients: '2 oz bourbon|0.25 oz simple syrup|2 dashes Angostura bitters|wood smoke|orange peel',
    instructions: '1. Stir bourbon, syrup, and bitters with ice. 2. Strain over a large cube in a smoke-rinsed glass, or smoke under a cloche. 3. Garnish with an orange peel.',
  },
];

function csvEscape(v: string | number) {
  const s = String(v ?? '');
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function main() {
  const headers = ['ID','slug','name','short_description','long_description','seo_description','base_spirit','category_primary','categories_all','tags','image_url','image_alt','glassware','garnish','technique','difficulty','flavor_strength','flavor_sweetness','flavor_tartness','flavor_bitterness','flavor_aroma','flavor_texture','notes','fun_fact','fun_fact_source','metadata_json','ingredients','instructions'];
  const rows = drafts.map((d, i) => [ `mw_review_003_${String(i+1).padStart(3,'0')}`, d.slug, d.name, d.short_description, d.long_description, d.seo_description, d.base_spirit, d.category_primary, d.categories_all, d.tags, '', d.image_alt, d.glassware, d.garnish, d.technique, d.difficulty, d.flavor_strength, d.flavor_sweetness, d.flavor_tartness, d.flavor_bitterness, d.flavor_aroma, d.flavor_texture, d.notes, d.fun_fact, d.fun_fact_source, '{}', d.ingredients, d.instructions ].map(csvEscape).join(','));
  const out = path.join(process.cwd(), 'data', 'review-batch-003.csv');
  fs.writeFileSync(out, [headers.join(','), ...rows].join('\n') + '\n');
  console.log(`Wrote ${drafts.length} → ${out}\n` + drafts.map(d => d.slug).join('\n'));
}
main();
